// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppMetadata = { slug: string, title: string, description: string, author: Author, categories: Array<Category>, };

export type ArtworkInput = { preview?: string, icon?: string, };

export type Author = { name: string, url?: string, };

export type Background = "transparent" | "glass";

export type BuildDeclaration = { metadata: AppMetadata, window: WindowInput, theme: Array<ThemeInput>, document: unknown, initial: unknown, commands: Array<CommandInput>, views: Views, };

export type BuildInput = { packageFormat: number, runtimeABI: number, declaration: BuildDeclaration, roles: BuildRoles, resources: Array<ResourceInput>, artwork: ArtworkInput, };

export type BuildRoles = { ui: string, style?: string, commands?: string, skin?: string, };

export type Category = "productivity" | "utilities" | "finance" | "media" | "games" | "developer-tools" | "education" | "business" | "personal" | "health" | "creative" | "music" | "other";

export type CommandInput = { name: string, description: string, args: unknown, };

export type FillRule = "nonzero" | "evenodd";

export type PathShape = { path: string, viewBox?: [number, number], fillRule?: FillRule, };

export type ResourceInput = { kind: ResourceKind, key: string, mediaType: string,
/**
 * A regular file beneath the private staging root, checked before reading.
 */
path: string, };

export type ResourceKind = "app" | "command";

export type ThemeInput = { token: string, color: string, };

export type Views = { export: boolean, icon: boolean, };

/**
 * A source declaration: the skin image is an imported URL. Acceptance resolves it
 * to a resource key; the stored window never keeps a source URL.
 */
export type WindowInput = { "kind": "standard", width: number, height: number, resizable?: boolean, lockAspect?: boolean, background?: Background, shape?: WindowShape, } | { "kind": "skin", width: number, height: number, image: string, };

export type WindowShape = string | PathShape;
