// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WindowInput } from "./app.generated";

export type BrowserEvent = { "type": "ready", title: string, window: WindowInput, } | { "type": "reply", id: string, json: string, } | { "type": "publication", json: string, } | { "type": "save", status: BrowserSaveStatus, error: string | null, } | { "type": "evaluate", input: string, } | { "type": "exported", id: string, file: string, } | { "type": "resource", id: string, size: number, media_type: string, offset: number, } | { "type": "error", id: string | null, error: string, };

export type BrowserRequest = { "type": "open", copy: string, source: string | null, } | { "type": "page", id: string, request: string, } | { "type": "flush", id: string, } | { "type": "export", id: string, } | { "type": "resource", id: string, route: ResourceRoute, key: string, offset: number | null, length: number | null, } | { "type": "evaluated", output: string | null, error: string | null, };

export type BrowserSaveStatus = "saved" | "saving" | "failed";

export type ResourceRoute = "app" | "attachment";
