// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Anchor = { before: string, } | { after: string, };

export type Batch = { ifVersion?: string, intents: Array<Intent>, };

export type Hunk = { retain: number, } | { insert: string, } | { delete: number, };

export type Intent = { "type": "set", path: Array<Segment>, value: unknown, from?: string, selection?: Selection, } | { "type": "insert", path: Array<Segment>, value: unknown, id?: string, at?: Anchor, index?: number, } | { "type": "remove", path: Array<Segment>, id?: string, index?: number, count?: number, } | { "type": "move", path: Array<Segment>, id: string, at?: Anchor, } | { "type": "clear", path: Array<Segment>, } | { "type": "increment", path: Array<Segment>, by: number, } | { "type": "replace", path: Array<Segment>, value: unknown, } | { "type": "setTheme", values: { [key in string]: string | null }, replace?: boolean, } | { "type": "importTheme", file: string, };

/**
 * A snapshot delivered to the page after its publication sequence.
 */
export type OwnerState = { sequence: number, version: string, value: unknown, theme: { [key in string]: string }, };

export type PatchOp = { "type": "set", path: Array<Segment>, value: unknown, } | { "type": "text", path: Array<Segment>, delta: Array<Hunk>, } | { "type": "remove", path: Array<Segment>, } | { "type": "insertRow", path: Array<Segment>, index: number, value: unknown, } | { "type": "deleteRow", path: Array<Segment>, id: string, } | { "type": "moveRow", path: Array<Segment>, id: string, index: number, };

export type Publication = { previous: number, sequence: number, version: string, ops: Array<PatchOp>, theme?: { [key in string]: string }, };

export type Segment = string | { id: string, } | { index: number, };

/**
 * A text selection in UTF-16 offsets.
 */
export type Selection = { start: number, end: number, };

/**
 * A shared theme file: the template it was made for and its palette.
 */
export type ThemeFile = { template: string, values: { [key in string]: string }, };
