// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppMetadata, Category, Views, WindowInput } from "./app.generated";
import type { Batch, Segment } from "./core.generated";

export type ArtworkTarget = "preview" | "icon";

export type AttachmentBytes = { bytes: string, };

export type AttachmentInfo = { mimeType: string, id: string, byteLength: number, };

export type AttachmentTotals = { count: number, bytes: number, };

/**
 * The template folders, the templates listed from them, and why each other `.slop` file
 * in them was left out.
 */
export type Catalog = { folders: Array<Folder>, templates: Array<Template>, issues: Array<string>, };

export type Code = "type_mismatch" | "out_of_range" | "path_not_found" | "invalid_key" | "exists" | "duplicate_id" | "invalid_request" | "invalid_id" | "invalid_path" | "invalid_schema" | "too_large" | "stale_base" | "invalid_bytes" | "missing_dependencies" | "engine_error" | "invalid_shape" | "requires_update" | "is_template" | "refused";

export type DescribeState = { metadata: AppMetadata, schema: Record<string, unknown>, version: string, value: unknown, theme: { [key in string]: string }, fields: Array<DescribedField>, commands: Record<string, { description: string; args: Record<string, unknown> }>, };

export type DescribedField = { path: Array<Segment>, kind: string, description: string | null, operations: Array<string>, };

export type EngineReply = EngineSuccess | Failure;

/**
 * One request on the engine's standard input. Protocol negotiation stays outside it.
 */
export type EngineRequest = { "method": "attachments.list", documentPath: string, } | { "method": "attachments.read", documentPath: string, attachmentID: string, } | { "method": "theme.export", documentPath: string, } | { "method": "get", documentPath: string, } | { "method": "batch", documentPath: string, batch: Batch, attachments?: Array<string>, } | { "method": "copy", documentPath: string, output: string, } | { "method": "export", documentPath: string, format: ExportFormat, output: string, } | { "method": "templates", } | { "method": "create", from: string, output: string, } | { "method": "inspect", file: string, } | { "method": "artwork.export", file: string, target: ArtworkTarget, output: string, } | { "method": "schema", file: string, } | { "method": "pack", stage: string, file: string, app: unknown, } | { "method": "validateApp", stage: string, app: unknown, } | { "method": "validateMetadata", metadata: AppMetadata, } | { "method": "describe", documentPath: string, } | { "method": "call", documentPath: string, command: string, args: unknown, } | { "method": "open", documentPath: string, } | { "method": "screenshot", documentPath: string, output: string, target: ArtworkTarget, ifPresent: boolean, };

/**
 * Every successful result names its method and carries all fields that method promises.
 */
export type EngineSuccess = { "method": "get", ok: True, state: GetState, } | { "method": "batch", ok: True, ids: Array<string>, } | { "method": "copy", ok: True, output: string, } | { "method": "export", ok: True, output: string, } | { "method": "theme.export", ok: True, state: ThemeExportState, } | { "method": "attachments.list", ok: True, state: Array<AttachmentInfo>, } | { "method": "attachments.read", ok: True, state: AttachmentBytes, } | { "method": "call", ok: True, result: unknown, ids: Array<string>, } | { "method": "templates", ok: True, catalog: Catalog, } | { "method": "create", ok: True, documentPath: string, } | { "method": "inspect", ok: True, info: InspectInfo, } | { "method": "artwork.export", ok: True, output: string | null, } | { "method": "schema", ok: True, schema: Record<string, unknown>, } | { "method": "pack", ok: True, } | { "method": "validateApp", ok: True, } | { "method": "validateMetadata", ok: True, } | { "method": "describe", ok: True, state: DescribeState, } | { "method": "open", ok: True, documentPath: string, } | { "method": "screenshot", ok: True, output: string | null, };

export type ExportFormat = "png" | "pdf";

/**
 * A classified failure. Unknown outcomes are explicit, never inferred from missing fields.
 */
export type Failure = { ok: False, error: string, code: OutcomeCode, reason?: Code, opIndex?: number, };

/**
 * `false` on the wire.
 */
export type False = false;

export type FileKind = "template" | "document";

/**
 * A template folder hosts list, whether or not it exists yet: `slop register` builds into
 * the installed one.
 */
export type Folder = { source: TemplateSource, path: string, };

/**
 * What an agent reads: the descriptor and declared colors, and the document's version,
 * value and effective colors.
 */
export type GetState = { schema: Record<string, unknown>, defaults: { [key in string]: string }, version: string, value: unknown, theme: { [key in string]: string }, };

/**
 * A file's kind, markers, app and sizes, and whether a live owner published its socket.
 */
export type InspectInfo = { kind: FileKind, packageFormat: number, runtimeABI: number, metadata: AppMetadata, window: WindowInput, views: Views, assets: Array<NamedSize>, artwork: Array<NamedSize>, defaults: { [key in string]: string }, attachments: AttachmentTotals, state: StateSizes, bytes: number, storedAssetBytes: number, live: boolean, };

export type NamedSize = { name: string, bytes: number, };

export type OutcomeCode = "rejected" | "owner_replaced" | "closing" | "save_failed" | "owner_invalidated" | "unknown_outcome";

export type StateSizes = { checkpointBytes: number, updates: number, updateBytes: number, };

/**
 * A listed template: what its manifest says, its file, and the folder it was listed from.
 */
export type Template = { slug: string, title: string, description: string, categories: Array<Category>, source: TemplateSource, path: string, };

/**
 * Where a listed template comes from: the starters bundled with the app, or the installed
 * templates folder that `slop register` builds into.
 */
export type TemplateSource = "bundled" | "installed";

export type ThemeExportState = { file: string, };

/**
 * `true` on the wire.
 */
export type True = true;
