// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WindowInput } from "./app.generated";
import type { Batch, Publication } from "./core.generated";
import type { True } from "./engine.generated";

export type CaptureMode = "preview" | "export" | "icon";

export type HostCaptureResult = { x: number, y: number, width: number, height: number, dedicated: boolean, };

/**
 * Private host-to-shell calls. Authored apps only receive ctx.
 */
export type HostRequest = { "method": "publish", payload: string, } | { "method": "flush" } | { "method": "undo" } | { "method": "redo" } | { "method": "prepareClose" } | { "method": "cancelClose" } | { "method": "close" } | { "method": "reloadInterface" } | { "method": "capture.begin", token: string, mode: CaptureMode, } | { "method": "capture.settle", token: string, } | { "method": "capture.restore", token: string, };

export type PageErrorKind = "operation" | "application";

export type PagePush = { "type": "publication", publication: Publication, } | { "type": "resync" };

export type PageRequest = { "method": "commands.run", name: string, args: unknown, } | { "method": "open", } | { "method": "apply", batch: Batch, } | { "method": "flush", } | { "method": "undo", } | { "method": "redo", } | { "method": "config", } | { "method": "attachments.put", bytes: string, } | { "method": "window.resize", width: number, height: number, } | { "method": "ready", } | { "method": "pageRecovered", } | { "method": "failed", error: string, } | { "method": "pageError", kind: PageErrorKind, error: string, };

export type PageSuccess = { "method": "commands.run", ok: True, sequence: number, ids: Array<string>, result: unknown, } | { "method": "open", ok: True, state: string, } | { "method": "apply", ok: True, sequence: number, ids: Array<string>, selectionStart?: number, selectionEnd?: number, } | { "method": "flush", ok: True, } | { "method": "undo", ok: True, sequence: number, } | { "method": "redo", ok: True, sequence: number, } | { "method": "config", ok: True, readOnly: boolean, runtimeABI: number, style: boolean, window: WindowInput, descriptor: object, } | { "method": "attachments.put", ok: True, id: string, byteLength: number, mimeType: string, } | { "method": "window.resize", ok: True, width: number, height: number, } | { "method": "ready", ok: True, } | { "method": "pageRecovered", ok: True, } | { "method": "failed", ok: True, } | { "method": "pageError", ok: True, };
