// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExportFormat } from "./engine.generated";

/**
 * The only fields a discovery reader interprets. Other fields are always ignored,
 * including values a future protocol could not represent in this build.
 */
export type Discovery = { documentPath: string, socket: string, };

export type SocketRequest = { "method": "attachments.list", protocol: number, documentPath: string, } | { "method": "attachments.read", protocol: number, documentPath: string, attachmentID: string, } | { "method": "theme.export", protocol: number, documentPath: string, } | { "method": "get", protocol: number, documentPath: string, } | { "method": "call", protocol: number, documentPath: string, command: string, args: unknown, } | { "method": "describe", protocol: number, documentPath: string, } | { "method": "batch", protocol: number, documentPath: string, ifVersion?: string, command?: string, ops: string, base?: string, attachments?: Array<string>, } | { "method": "export", protocol: number, documentPath: string, format: ExportFormat, output: string, };
