import { style, globalStyle } from "@vanilla-extract/css";
import theme from "./theme";
const t=theme.vars;
globalStyle("*", {boxSizing:"border-box"});
globalStyle("html, body", {margin:0,minHeight:"100%",background:t.surface,color:t.ink,fontFamily:"-apple-system, BlinkMacSystemFont, sans-serif",fontSize:15});
globalStyle("button, input", {font:"inherit"});
export const paper=style({padding:"34px 32px 28px",maxWidth:760,margin:"0 auto","@media":{"(max-width: 420px)":{padding:"26px 18px"}}});
export const eyebrow=style({fontSize:11,fontWeight:650,letterSpacing:"0.14em",textTransform:"uppercase",color:t.accent,marginBottom:14});
export const title=style({width:"100%",fontFamily:"Georgia, serif",fontSize:32,lineHeight:1.2,fontWeight:400,border:0,background:"transparent",color:t.ink,padding:"4px 0",outlineOffset:4,":focus-visible":{outline:`2px solid ${t.accent}`}});
export const summary=style({color:t.muted,fontSize:13,margin:"14px 0 28px"});
export const list=style({listStyle:"none",padding:0,margin:0,borderTop:`1px solid ${t.rule}`});
export const row=style({display:"grid",gridTemplateColumns:"24px minmax(0,1fr) auto",alignItems:"center",gap:10,minHeight:62,borderBottom:`1px solid ${t.rule}`,padding:"9px 0"});
export const check=style({width:21,height:21,border:`1.5px solid ${t.muted}`,borderRadius:5,background:"transparent",color:t.surface,display:"grid",placeItems:"center",cursor:"pointer",padding:0,selectors:{'&[data-state="checked"]':{background:t.accent,borderColor:t.accent}},":focus-visible":{outline:`2px solid ${t.accent}`,outlineOffset:3}});
export const text=style({width:"100%",minWidth:0,border:0,background:"transparent",padding:"8px 0",color:t.ink,":focus-visible":{outline:`2px solid ${t.accent}`,outlineOffset:2},selectors:{'&[data-done="true"]':{textDecoration:"line-through",color:t.muted}}});
export const actions=style({display:"flex",gap:2});
export const small=style({border:0,background:"transparent",color:t.muted,padding:"8px 5px",cursor:"pointer",borderRadius:4,":hover":{background:t.panel,color:t.ink},":disabled":{opacity:0.3,cursor:"default"},":focus-visible":{outline:`2px solid ${t.accent}`}});
export const add=style({display:"flex",gap:10,marginTop:22});
export const entry=style({minWidth:0,flex:1,border:`1px solid ${t.rule}`,borderRadius:6,padding:"11px 12px",background:"transparent",color:t.ink,":focus-visible":{outline:`2px solid ${t.accent}`,outlineOffset:2}});
export const button=style({border:0,borderRadius:6,padding:"10px 15px",background:t.accent,color:"white",cursor:"pointer",":disabled":{opacity:0.45,cursor:"default"},":focus-visible":{outline:`2px solid ${t.accent}`,outlineOffset:3}});
export const footer=style({display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,marginTop:32,fontSize:12,color:t.muted});
export const error=style({color:"#a13224",fontSize:13,lineHeight:1.4});
