import { style, globalStyle } from "@vanilla-extract/css";
import theme from "./theme";
const t=theme.vars;
globalStyle("*",{boxSizing:"border-box"});
globalStyle("html, body",{margin:0,minHeight:"100%",background:t.surface,color:t.ink,fontFamily:"-apple-system, BlinkMacSystemFont, sans-serif",fontSize:14});
globalStyle("button, input",{font:"inherit"});
const focus={outline:`2px solid ${t.accent}`,outlineOffset:3};
export const paper=style({maxWidth:820,margin:"0 auto",padding:"30px 28px","@media":{"(max-width: 450px)":{padding:"24px 16px"}}});
export const eyebrow=style({fontSize:11,fontWeight:650,letterSpacing:".14em",textTransform:"uppercase",color:t.accent,marginBottom:12});
export const title=style({width:"100%",fontFamily:"Georgia, serif",fontSize:32,border:0,padding:"4px 0",background:"transparent",color:t.ink,":focus-visible":focus});
export const overview=style({display:"flex",alignItems:"end",justifyContent:"space-between",gap:16,margin:"24px 0 22px",flexWrap:"wrap"});
export const total=style({fontSize:34,fontVariantNumeric:"tabular-nums",letterSpacing:"-.04em",margin:"4px 0"});
export const muted=style({fontSize:12,color:t.muted});
export const currencies=style({display:"flex",gap:3});
export const currency=style({border:0,borderRadius:4,padding:"7px 9px",background:"transparent",color:t.muted,cursor:"pointer",selectors:{'&[data-state="active"]':{background:t.panel,color:t.ink}},":focus-visible":focus});
export const toolbar=style({display:"flex",gap:8,alignItems:"center",justifyContent:"space-between",padding:"12px 0",borderTop:`1px solid ${t.rule}`});
export const selection=style({display:"flex",gap:8,alignItems:"center"});
export const check=style({width:20,height:20,flexShrink:0,border:`1px solid ${t.muted}`,borderRadius:4,background:"transparent",color:"white",padding:0,display:"grid",placeItems:"center",cursor:"pointer",selectors:{'&[data-state="checked"]':{background:t.accent,borderColor:t.accent}},":focus-visible":focus});
export const button=style({border:0,borderRadius:5,padding:"9px 12px",background:t.accent,color:"white",cursor:"pointer",":disabled":{opacity:.4,cursor:"default"},":focus-visible":focus});
export const list=style({padding:0,margin:0,listStyle:"none"});
export const row=style({display:"grid",gridTemplateColumns:"20px minmax(0,1fr) auto",gap:12,alignItems:"start",padding:"15px 0",borderTop:`1px solid ${t.rule}`});
export const merchant=style({border:0,background:"transparent",padding:0,width:"100%",minWidth:0,fontWeight:550,color:t.ink,":focus-visible":focus});
export const note=style({fontSize:12,margin:"5px 0",color:t.muted,overflowWrap:"anywhere"});
export const amount=style({fontVariantNumeric:"tabular-nums",textAlign:"right",fontWeight:550});
export const actions=style({display:"flex",gap:5,marginTop:7,flexWrap:"wrap"});
export const small=style({border:0,background:"transparent",color:t.muted,padding:"4px 7px",cursor:"pointer",borderRadius:4,":hover":{background:t.panel,color:t.ink},":disabled":{opacity:.35,cursor:"default"},":focus-visible":focus});
export const form=style({display:"grid",gridTemplateColumns:"minmax(0,1fr) 100px",gap:10,paddingTop:22,borderTop:`1px solid ${t.rule}`});
export const entry=style({width:"100%",minWidth:0,padding:"10px 11px",border:`1px solid ${t.rule}`,borderRadius:5,color:t.ink,background:"transparent",":focus-visible":focus});
export const footer=style({display:"flex",justifyContent:"space-between",flexWrap:"wrap",gap:8,marginTop:26,color:t.muted,fontSize:12});
export const error=style({color:"#a13224",fontSize:13});
