// Generated by bun run schema:generate. Do not edit.
let bridgeMethods: Set<String> = ["theme.load","theme.save","runtimeRecovered","window.resize","config","ready","load","append","checkpoint","status","failed","runtimeError"]
