// Generated by bun run schema:generate. Do not edit.
let bridgeMethods: Set<String> = ["attachments.put","attachments.read","attachments.list","theme.load","theme.save","runtimeRecovered","window.resize","config","ready","load","append","checkpoint","status","failed","runtimeError"]
