import { defineTheme } from "@hitslop/runtime/theme";

export default defineTheme({
  surface: "#ffffff",
  paper: "#ffffff",
  control: "#f5eff4",
  border: "#e5dce4",
  ink: "#382337",
  muted: "#746574",
  dim: "#827381",
  rule: "#ebe3e9",
  ruleStrong: "#d8cbd6",
  stamp: "#642b4b",
  stampSoft: "#f1e3ed",
  gold: "#914467",
  goldMuted: "#b9aab6",
  read: "#316e5c",
  readSoft: "#e4f1eb",
  reading: "#6f4795",
  readingSoft: "#eee7f8",
  danger: "#b33655",
  onAccent: "#ffffff",
  font: '"Avenir Next", Avenir, "Helvetica Neue", sans-serif',
  headingFont: '"Reading Newsreader", Georgia, serif',
});
