import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { $ } from "bun";
import { z } from "zod";
import { SlopManifestSchema } from "./manifest.ts";

const packageRoot = resolve(import.meta.dir, "..");
const repositoryRoot = resolve(packageRoot, "../..");
const generated = resolve(packageRoot, "generated");
await mkdir(generated, { recursive: true });

await generate({
  zodSchema: SlopManifestSchema,
  schemaName: "manifest.schema.json",
  swiftName: "SlopManifest.generated.swift",
  id: "https://hitslop.app/schemas/v1/manifest.schema.json",
  title: "SlopManifest",
  description: "The framework-neutral manifest for hitSlop web documents.",
  transformSwift: addSendable,
  transformSchema: stampUniqueItems,
});

async function generate(options: {
  zodSchema: z.ZodType;
  schemaName: string;
  swiftName: string;
  id: string;
  title: string;
  description: string;
  transformSchema?: (node: unknown, root: Record<string, unknown>) => void;
  transformSwift?: (source: string) => string;
}): Promise<void> {
  const schema = z.toJSONSchema(options.zodSchema, { target: "draft-2020-12", reused: "ref", io: "input" }) as Record<string, unknown>;
  Object.assign(schema, { $id: options.id, title: options.title, description: options.description });
  options.transformSchema?.(schema, schema);
  const schemaPath = resolve(generated, options.schemaName);
  const swiftOutput = resolve(repositoryRoot, "packages/apple/Sources/HitSlopCore/Generated", options.swiftName);
  const swiftSchema = resolve(repositoryRoot, "packages/apple/Sources/HitSlopCore/Resources/manifest.schema.json");
  const catalogSchema = resolve(repositoryRoot, "apps/catalog/public/schemas/v1/manifest.schema.json");
  await mkdir(resolve(swiftOutput, ".."), { recursive: true });
  await mkdir(resolve(swiftSchema, ".."), { recursive: true });
  await mkdir(resolve(catalogSchema, ".."), { recursive: true });
  const serialized = `${JSON.stringify(schema, null, 2)}\n`;
  await writeFile(schemaPath, serialized);
  await writeFile(swiftSchema, serialized);
  await writeFile(catalogSchema, serialized);
  await $`bunx quicktype --src-lang schema --lang swift --top-level ${options.title} --access-level public --src ${schemaPath} --out ${swiftOutput}`;
  const generatedSwift = stripQuicktypeHelpers(await Bun.file(swiftOutput).text());
  await Bun.write(swiftOutput, options.transformSwift ? options.transformSwift(generatedSwift) : generatedSwift);
}

function stampUniqueItems(node: unknown, root: Record<string, unknown>): void {
  if (!node || typeof node !== "object") return;
  const record = node as Record<string, unknown>;
  if (record.type === "array" && record.maxItems === 2 && !("uniqueItems" in record)) {
    record.uniqueItems = true;
  }
  const resolved = resolveRef(record, root);
  if (resolved && resolved !== record) stampUniqueItems(resolved, root);
  for (const value of Object.values(record)) {
    if (value !== root) stampUniqueItems(value, root);
  }
}

function resolveRef(property: Record<string, unknown>, root: Record<string, unknown>): Record<string, unknown> | undefined {
  const ref = property.$ref;
  if (typeof ref !== "string" || !ref.startsWith("#/")) return undefined;
  let current: unknown = root;
  for (const part of ref.slice(2).split("/")) {
    if (!current || typeof current !== "object") return undefined;
    current = (current as Record<string, unknown>)[part];
  }
  return current && typeof current === "object" ? current as Record<string, unknown> : undefined;
}

function addSendable(source: string): string {
  return source
    .replaceAll(": Codable {", ": Codable, Sendable {")
    .replaceAll(": String, Codable {", ": String, Codable, Sendable, CaseIterable {");
}

function stripQuicktypeHelpers(source: string): string {
  const withoutBanner = source.replace(/^\/\/ This file was generated[\s\S]*?(?=import Foundation)/, "");
  const withoutHelpers = withoutBanner
    .replace(/\n\/\/ MARK: .* convenience initializers and mutators[\s\S]*?(?=\n(\/\/ MARK: |public (?:struct|enum|func)|$))/g, "\n")
    .replace(/\n\/\/ MARK: - Helper functions[\s\S]*$/, "\n");
  return `// Generated by bun run schema:generate. Do not edit.\n${withoutHelpers.trim()}\n`;
}
