import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { quicktype, InputData, JSONSchemaInput, FetchingJSONSchemaStore } from "quicktype-core";
import type { TSchema } from "typebox";
import { dataSchemaFromJSON } from "./data.ts";
import { SlopManifestSchema } from "./manifest.ts";
import { documentSkillContent } from "./document-skill.ts";
import { BridgeRequestSchema, BridgeMethodSchema, BridgeErrorCodeSchema, protocolVersion } from "./bridge.ts";

const packageRoot = resolve(import.meta.dir, "..");
const sourceRoot = resolve(packageRoot, "../..");
const repositoryRoot = process.env.HITSLOP_GENERATED_ROOT ? resolve(process.env.HITSLOP_GENERATED_ROOT) : sourceRoot;
const generated = resolve(repositoryRoot, "packages/schema/generated");
await mkdir(generated, { recursive: true });

const swiftDocumentSkill = resolve(repositoryRoot, "apps/apple/Packages/HitSlopApple/Sources/HitSlopCore/Resources/hitslop-document.SKILL.md");
await mkdir(resolve(swiftDocumentSkill, ".."), { recursive: true });
await writeFile(swiftDocumentSkill, documentSkillContent);

const runtimeResources = resolve(repositoryRoot, "apps/apple/Packages/HitSlopApple/Sources/HitSlopRuntime/Resources");
await mkdir(runtimeResources, { recursive: true });
const bridgeSchema = JSON.stringify(dataSchemaFromJSON(BridgeRequestSchema), null, 2) + "\n";
await writeFile(resolve(generated, "bridge-request.schema.json"), bridgeSchema);
await writeFile(resolve(runtimeResources, "bridge-request.schema.json"), bridgeSchema);
const guest = await Bun.build({ entrypoints: [resolve(sourceRoot, "packages/runtime/src/host-bridge.ts")], target: "browser", format: "iife", minify: true });
if (!guest.success) throw new Error(guest.logs.join("\n"));
await writeFile(resolve(runtimeResources, "host-bridge.js"), await guest.outputs[0]!.text());
const cases = (values: readonly string[]) => values.map((value) => `    case ${value.replace(/[._]([a-z])/g, (_, c: string) => c.toUpperCase())} = ${JSON.stringify(value)}`).join("\n");
await writeFile(resolve(runtimeResources, "../BridgeContract.generated.swift"), `// Generated by bun run schema:generate. Do not edit.\nimport Foundation\n\nlet slopProtocolVersion = ${protocolVersion}\nenum SlopBridgeMethod: String, CaseIterable, Sendable {\n${cases(BridgeMethodSchema.enum)}\n}\nenum SlopBridgeErrorCode: String, Sendable {\n${cases(BridgeErrorCodeSchema.enum)}\n}\n`);

await generate({
  schema: SlopManifestSchema,
  schemaName: "manifest.schema.json",
  swiftName: "SlopManifest.generated.swift",
  id: "https://api.hitslop.com/schemas/v1/manifest.schema.json",
  title: "SlopManifest",
  description: "The framework-neutral manifest for hitSlop web documents.",
});

async function generate(options: {
  schema: TSchema;
  schemaName: string;
  swiftName: string;
  id: string;
  title: string;
  description: string;
}): Promise<void> {
  const schema = dataSchemaFromJSON(options.schema);
  Object.assign(schema, { $id: options.id, title: options.title, description: options.description });
  const schemaPath = resolve(generated, options.schemaName);
  const swiftOutput = resolve(repositoryRoot, "apps/apple/Packages/HitSlopApple/Sources/HitSlopCore/Generated", options.swiftName);
  const swiftSchema = resolve(repositoryRoot, "apps/apple/Packages/HitSlopApple/Sources/HitSlopCore/Resources/manifest.schema.json");
  const publicSchema = resolve(repositoryRoot, "apps/firebase/public/schemas/v1/manifest.schema.json");
  await mkdir(resolve(swiftOutput, ".."), { recursive: true });
  await mkdir(resolve(swiftSchema, ".."), { recursive: true });
  await mkdir(resolve(publicSchema, ".."), { recursive: true });
  const serialized = `${JSON.stringify(schema, null, 2)}\n`;
  await writeFile(schemaPath, serialized);
  await writeFile(swiftSchema, serialized);
  await writeFile(publicSchema, serialized);
  const input = new JSONSchemaInput(new FetchingJSONSchemaStore());
  await input.addSource({ name: options.title, schema: serialized });
  const inputData = new InputData();
  inputData.addInput(input);
  const result = await quicktype({
    inputData, lang: "swift",
    rendererOptions: { "access-level": "public", sendable: "true", initializers: "false" },
  });
  // Catalog enumeration is app-specific; synthesize in the same file as the enum.
  await writeFile(swiftOutput, "// Generated by bun run schema:generate. Do not edit.\n" + result.lines.join("\n") + "\n\nextension SlopCategory: CaseIterable {}\n");
}
