import { expect, test } from "bun:test";
import { discoverSlops } from "../dev-gallery.ts";

test("only supported examples appear in the active gallery", async () => {
  expect((await discoverSlops()).map(slop => slop.slug)).toEqual([
    "alien-radio",
    "ambient-sound-mixer",
    "assignment-tracker",
    "bullet-journal",
    "codex-pet",
    "contact-card",
    "countdown-milestones",
    "daily-planner",
    "pros-cons-sheet",
    "eisenhower-matrix",
    "expense-log",
    "five-minute-journal",
    "flashcards",
    "grocery-list",
    "habit-tracker",
    "harada-method",
    "invoice",
    "kanban-board",
    "markdown-editor",
    "meeting-notes",
    "metronome-tapper",
    "mood-log",
    "morning-pages",
    "packing-list",
    "personal-budget",
    "pixel-art",
    "pocket-sheet",
    "focus-timer",
    "quick-checklist",
    "reading-tracker",
    "recipe",
    "resume",
    "school-schedule",
    "soma-amp",
    "subscription-tracker",
    "trip-itinerary",
    "water-tracker",
    "weekly-planner",
    "wordle",
    "workout-planner",
  ]);
});
