import { defineTheme } from "@hitslop/runtime/theme";

export default defineTheme({
  surface: "#efe8db",
  paper: "#fffdf8",
  paperSoft: "#f7f1e6",
  ink: "#231f1c",
  muted: "#6f6a62",
  dim: "#a39d93",
  rule: "color-mix(in srgb, var(--slop-ink) 12%, transparent)",
  ruleStrong: "color-mix(in srgb, var(--slop-ink) 28%, transparent)",
  border: "#ddd6c8",
  danger: "#b42318",
  onPaper: "#fffdf8",
  q1Accent: "#c2410c",
  q1Bg: "#fff7ed",
  q1Border: "#fed7aa",
  q2Accent: "#0f766e",
  q2Bg: "#f0fdfa",
  q2Border: "#99f6e4",
  q3Accent: "#b45309",
  q3Bg: "#fefce8",
  q3Border: "#fef08a",
  q4Accent: "#64748b",
  q4Bg: "#f8fafc",
  q4Border: "#e2e8f0",
  font: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif',
  headingFont: 'Georgia, "Iowan Old Style", "Times New Roman", serif',
  mono: 'ui-monospace, "SFMono-Regular", Menlo, monospace',
});
