// Generated by bun spikes/engine-placement/generate.ts. Do not edit.
import Foundation
public struct SetOp: Codable, Sendable {
  public let path: [JSONValue]
  public let value: JSONValue
  public init(path: [JSONValue], value: JSONValue) { self.path = path; self.value = value }
}
public struct ClearOp: Codable, Sendable {
  public let path: [JSONValue]
  public init(path: [JSONValue]) { self.path = path }
}
public struct AssignOp: Codable, Sendable {
  public let path: [JSONValue]
  public let value: JSONValue
  public init(path: [JSONValue], value: JSONValue) { self.path = path; self.value = value }
}
public struct SpliceOp: Codable, Sendable {
  public let path: [JSONValue]
  public let index: Int
  public let deleteCount: Int
  public let text: String
  public init(path: [JSONValue], index: Int, deleteCount: Int, text: String) { self.path = path; self.index = index; self.deleteCount = deleteCount; self.text = text }
}
public struct MarkOp: Codable, Sendable {
  public let path: [JSONValue]
  public let start: Int
  public let end: Int
  public let key: String
  public let value: JSONValue
  public init(path: [JSONValue], start: Int, end: Int, key: String, value: JSONValue) { self.path = path; self.start = start; self.end = end; self.key = key; self.value = value }
}
public struct InsertOp: Codable, Sendable {
  public let path: [JSONValue]
  public let index: Int
  public let id: String
  public let value: JSONValue
  public init(path: [JSONValue], index: Int, id: String, value: JSONValue) { self.path = path; self.index = index; self.id = id; self.value = value }
}
public struct RemoveOp: Codable, Sendable {
  public let path: [JSONValue]
  public let index: Int
  public init(path: [JSONValue], index: Int) { self.path = path; self.index = index }
}
public struct MoveOp: Codable, Sendable {
  public let path: [JSONValue]
  public let from: Int
  public let to: Int
  public init(path: [JSONValue], from: Int, to: Int) { self.path = path; self.from = from; self.to = to }
}
public struct IncrementOp: Codable, Sendable {
  public let path: [JSONValue]
  public let amount: Double
  public init(path: [JSONValue], amount: Double) { self.path = path; self.amount = amount }
}
public enum Operation: Codable, Sendable {
  case set(SetOp)
  case clear(ClearOp)
  case assign(AssignOp)
  case splice(SpliceOp)
  case mark(MarkOp)
  case insert(InsertOp)
  case remove(RemoveOp)
  case move(MoveOp)
  case increment(IncrementOp)
  enum Keys: String, CodingKey { case type }
  public init(from decoder: Decoder) throws {
    let key = try decoder.container(keyedBy: Keys.self).decode(String.self, forKey: .type)
    switch key {
    case "set": self = .set(try SetOp(from: decoder))
    case "clear": self = .clear(try ClearOp(from: decoder))
    case "assign": self = .assign(try AssignOp(from: decoder))
    case "splice": self = .splice(try SpliceOp(from: decoder))
    case "mark": self = .mark(try MarkOp(from: decoder))
    case "insert": self = .insert(try InsertOp(from: decoder))
    case "remove": self = .remove(try RemoveOp(from: decoder))
    case "move": self = .move(try MoveOp(from: decoder))
    case "increment": self = .increment(try IncrementOp(from: decoder))
    default: throw SpikeError("Unknown operation: \(key)")
    }
  }
  public func encode(to encoder: Encoder) throws {
    var c = encoder.container(keyedBy: Keys.self)
    switch self {
    case .set(let v): try c.encode("set", forKey: .type); try v.encode(to: encoder)
    case .clear(let v): try c.encode("clear", forKey: .type); try v.encode(to: encoder)
    case .assign(let v): try c.encode("assign", forKey: .type); try v.encode(to: encoder)
    case .splice(let v): try c.encode("splice", forKey: .type); try v.encode(to: encoder)
    case .mark(let v): try c.encode("mark", forKey: .type); try v.encode(to: encoder)
    case .insert(let v): try c.encode("insert", forKey: .type); try v.encode(to: encoder)
    case .remove(let v): try c.encode("remove", forKey: .type); try v.encode(to: encoder)
    case .move(let v): try c.encode("move", forKey: .type); try v.encode(to: encoder)
    case .increment(let v): try c.encode("increment", forKey: .type); try v.encode(to: encoder)
    }
  }
  public var path: [JSONValue] { switch self {
    case .set(let v): v.path
    case .clear(let v): v.path
    case .assign(let v): v.path
    case .splice(let v): v.path
    case .mark(let v): v.path
    case .insert(let v): v.path
    case .remove(let v): v.path
    case .move(let v): v.path
    case .increment(let v): v.path
  } }
}
