import { defineTheme } from "@hitslop/runtime/theme";
export default defineTheme({
  paper: "#f7f9fd",
  paperSoft: "#edf1f8",
  ink: "#172e55",
  muted: "#60708a",
  dim: "#8c9ab0",
  accent: "#2449a5",
  onAccent: "#ffffff",
  rule: "#dce4f0",
  border: "#ccd7e7",
  danger: "#b43850",
  sky: "#c8e7ff",
  coral: "#ffd2c8",
  mint: "#c6eedb",
  lilac: "#e0d7fc",
  font: '"Avenir Next", Avenir, "Helvetica Neue", sans-serif',
  headingFont: '"Avenir Next", Avenir, sans-serif',
  mono: 'ui-monospace, "SFMono-Regular", monospace',
});
