import { defineTheme } from "@hitslop/runtime/theme";
export default defineTheme({
  surface: "#ffffff",
  paper: "#ffffff",
  panel: "#f6f2fa",
  ink: "#32223f",
  muted: "#776781",
  rule: "#e9e0ee",
  plum: "#533163",
  plumDeep: "#3e224c",
  lilac: "#e5d6f4",
  accent: "#a64038",
  coral: "#ffc1ae",
  mint: "#c5e9d9",
  done: "#326554",
  onAccent: "#ffffff",
  danger: "#a43e42",
  font: '"Avenir Next", Avenir, "Helvetica Neue", sans-serif',
  mono: 'ui-monospace, "SFMono-Regular", Menlo, monospace',
});
