import { variants, Segment, Anchor, textFields } from "./contract";

// The deliberately small generator fails on unsupported types. It generates the
// Rust deserialization envelope; descriptor interpretation stays inside the core.
const upper = (s: string) => s[0]!.toUpperCase() + s.slice(1);
const optional = (s: object) => (s as any)["~optional"] === true;
function rust(schema: any): string {
  let result: string;
  if (schema === Anchor) result = "Anchor";
  else if (schema.type === "array") result = `Vec<${schema.items === Segment ? "Segment" : rust(schema.items)}>`;
  else if (schema.type === "string") result = "String";
  else if (schema.type === "integer") result = schema.minimum >= 0 ? "usize" : "i64";
  else if (schema.anyOf && schema.anyOf[0]?.properties?.before) result = "Anchor";
  else if (Object.keys(schema).length === 0) result = "Value";
  else throw new Error(`Unhandled wire type: ${JSON.stringify(schema)}`);
  return optional(schema) ? `Option<${result}>` : result;
}
const union = (name: string, schema: any) => `#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(untagged, deny_unknown_fields)]
pub enum ${name} {
${schema.anyOf.map((s: any) => s.type === "string" ? "    Key(String)," :
  `    ${upper(Object.keys(s.properties)[0]!)} { ${Object.entries(s.properties).map(([k,v]) => `${k}: ${rust(v)}`).join(", ")} },`).join("\n")}
}`;
const source = `// Generated by bun spikes/hitslop-core/generate.ts. Do not edit.
use serde::{Serialize, Deserialize};
use serde_json::Value;
${union("Segment", Segment)}
${union("Anchor", Anchor)}
#[derive(Clone, Debug, Deserialize)]
#[serde(tag = "type", rename_all = "lowercase", deny_unknown_fields)]
pub enum Intent {
${Object.entries(variants).map(([kind, fields]) => `    ${upper(kind)} { ${Object.entries(fields).map(([key,schema]) => `${key}: ${rust(schema)}`).join(", ")} },`).join("\n")}
}
impl Intent {
    pub fn path(&self) -> &[Segment] { match self {
${Object.keys(variants).map((kind) => `        Self::${upper(kind)} { path, .. } => path,`).join("\n")}
    } }
}
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Batch { pub intents: Vec<Intent> }
#[derive(Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
#[allow(non_snake_case)]
pub struct TextRequest { ${Object.entries(textFields).map(([key,schema]) => `pub ${key}: ${rust(schema)}`).join(", ")} }
`;
const out = new URL("./core/src/wire.generated.rs", import.meta.url);
if (process.argv.includes("--check")) {
  if (await Bun.file(out).text() !== source) throw new Error("Rust spike wire drift");
} else await Bun.write(out, source);
