import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { quicktype, InputData, JSONSchemaInput, FetchingJSONSchemaStore } from "quicktype-core";
import { SlopManifestSchema } from "../../packages/schema/src/index";
import { swiftContracts } from "./swift-contracts";
import { platformValidatorSource } from "./platform-validator";
import { BridgeMethods, BridgeRequestSchema } from "../../packages/schema/src/bridge";
import {
  SocketRequestSchema,
  SocketReplySchema,
  SocketDiscoverySchema,
} from "../../packages/schema/src/socket";
import {
  RuntimeIdentitySchema,
  RuntimeRequirementsSchema,
  RuntimeCapabilitiesSchema,
} from "../../packages/schema/src/runtime";
const root = resolve(import.meta.dir, "../..");
export async function generateContracts(check = false) {
  const schema = JSON.stringify(SlopManifestSchema, null, 2) + "\n";
  const input = new JSONSchemaInput(new FetchingJSONSchemaStore());
  await input.addSource({ name: "SlopManifest", schema });
  const inputData = new InputData();
  inputData.addInput(input);
  const result = await quicktype({
    inputData,
    lang: "swift",
    rendererOptions: { "access-level": "public", sendable: "true" },
  });
  const outputs = {
    "packages/schema/generated/runtime.schema.json":
      JSON.stringify(
        {
          identity: RuntimeIdentitySchema,
          requirements: RuntimeRequirementsSchema,
          capabilities: RuntimeCapabilitiesSchema,
        },
        null,
        2,
      ) + "\n",
    "apps/apple/Packages/HitSlopApple/Sources/HitSlopCore/Generated/Runtime.generated.swift":
      "// Generated by bun run schema:generate. Do not edit.\nimport Foundation\n" +
      Object.entries({
        runtimeIdentitySchema: RuntimeIdentitySchema,
        runtimeRequirementsSchema: RuntimeRequirementsSchema,
        runtimeCapabilitiesSchema: RuntimeCapabilitiesSchema,
      })
        .map(
          ([name, schema]) =>
            `public var ${name}: [String: Any] { try! JSONSerialization.jsonObject(with: Data(#"${JSON.stringify(schema)}"#.utf8)) as! [String: Any] }\n`,
        )
        .join(""),
    "packages/schema/generated/socket.schema.json":
      JSON.stringify(
        {
          request: SocketRequestSchema,
          reply: SocketReplySchema,
          discovery: SocketDiscoverySchema,
        },
        null,
        2,
      ) + "\n",
    "apps/apple/Packages/HitSlopApple/Sources/HitSlopCore/Generated/Socket.generated.swift":
      "// Generated by bun run schema:generate. Do not edit.\nimport Foundation\n" +
      Object.entries({
        socketRequestSchema: SocketRequestSchema,
        socketReplySchema: SocketReplySchema,
        socketDiscoverySchema: SocketDiscoverySchema,
      })
        .map(
          ([name, schema]) =>
            `public var ${name}: [String: Any] { try! JSONSerialization.jsonObject(with: Data(#"${JSON.stringify(schema)}"#.utf8)) as! [String: Any] }\n`,
        )
        .join(""),
    "apps/apple/Packages/HitSlopApple/Sources/HitSlopCore/Generated/PlatformValidation.generated.swift":
      "// Generated by bun run schema:generate. Do not edit.\n" +
      platformValidatorSource +
      '\npublic var manifestValidationSchema: [String: Any] { try! JSONSerialization.jsonObject(with: Data(#"' +
      JSON.stringify(SlopManifestSchema) +
      '"#.utf8)) as! [String: Any] }\npublic var bridgeValidationSchema: [String: Any] { try! JSONSerialization.jsonObject(with: Data(#"' +
      JSON.stringify(BridgeRequestSchema) +
      '"#.utf8)) as! [String: Any] }\n',
    "packages/schema/generated/manifest.schema.json": schema,
    "packages/schema/generated/bridge.schema.json":
      JSON.stringify(BridgeRequestSchema, null, 2) + "\n",
    "apps/apple/Packages/HitSlopApple/Sources/HitSlopCore/Generated/SlopManifest.generated.swift":
      "// Generated by bun run schema:generate. Do not edit.\n" +
      result.lines.join("\n").trimEnd() +
      "\n\nextension SlopCategory: CaseIterable {}\n",
    "apps/apple/Packages/HitSlopApple/Sources/HitSlopCore/Generated/Contracts.generated.swift":
      swiftContracts(SocketRequestSchema, SocketReplySchema, SocketDiscoverySchema, Object.keys(BridgeMethods)),
  };
  for (const [name, value] of Object.entries(outputs)) {
    const path = resolve(root, name);
    if (check) {
      if ((await readFile(path, "utf8")) !== value) throw new Error(`Generated drift: ${name}`);
    } else {
      await mkdir(dirname(path), { recursive: true });
      await writeFile(path, value);
    }
  }
}

if (import.meta.main) await generateContracts(process.argv.includes("--check"));
