import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { dataSchemaFromJSON } from "../data.ts";
import {
  BridgeRequestSchema,
  BridgeMethodSchema,
  BridgeErrorCodeSchema,
  protocolVersion,
} from "../bridge.ts";

export async function generateBridge(
  repositoryRoot: string,
  sourceRoot: string,
  generated: string,
) {
  const runtimeResources = resolve(
    repositoryRoot,
    "apps/apple/Packages/HitSlopApple/Sources/HitSlopRuntime/Resources",
  );
  await mkdir(runtimeResources, { recursive: true });
  const bridgeSchema = JSON.stringify(dataSchemaFromJSON(BridgeRequestSchema), null, 2) + "\n";
  await writeFile(resolve(generated, "bridge-request.schema.json"), bridgeSchema);
  await writeFile(resolve(runtimeResources, "bridge-request.schema.json"), bridgeSchema);
  const guest = await Bun.build({
    entrypoints: [resolve(sourceRoot, "packages/runtime/src/host-bridge.ts")],
    target: "browser",
    format: "iife",
    minify: true,
  });
  if (!guest.success) throw new Error(guest.logs.join("\n"));
  await writeFile(resolve(runtimeResources, "host-bridge.js"), await guest.outputs[0]!.text());
  const cases = (values: readonly string[]) =>
    values
      .map(
        (value) =>
          `    case ${value.replace(/[._]([a-z])/g, (_, c: string) => c.toUpperCase())} = ${JSON.stringify(value)}`,
      )
      .join("\n");
  await writeFile(
    resolve(runtimeResources, "../BridgeContract.generated.swift"),
    `// Generated by bun run schema:generate. Do not edit.\nimport Foundation\n\nlet slopProtocolVersion = ${protocolVersion}\nenum SlopBridgeMethod: String, CaseIterable, Sendable {\n${cases(BridgeMethodSchema.enum)}\n}\nenum SlopBridgeErrorCode: String, Sendable {\n${cases(BridgeErrorCodeSchema.enum)}\n}\n`,
  );
}
