import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { quicktype, InputData, JSONSchemaInput, FetchingJSONSchemaStore } from "quicktype-core";
import type { TSchema } from "typebox";
import { dataSchemaFromJSON } from "../data.ts";
import { SlopManifestSchema } from "../manifest.ts";

export async function generateModels(
  repositoryRoot: string,
  sourceRoot: string,
  generated: string,
) {
  await generate({
    schema: SlopManifestSchema,
    schemaName: "manifest.schema.json",
    swiftName: "SlopManifest.generated.swift",
    id: "https://api.hitslop.com/schemas/v1/manifest.schema.json",
    title: "SlopManifest",
    description: "The framework-neutral manifest for hitSlop web documents.",
  });

  async function generate(options: {
    schema: TSchema;
    schemaName: string;
    swiftName: string;
    id: string;
    title: string;
    description: string;
  }): Promise<void> {
    const schema = dataSchemaFromJSON(options.schema);
    Object.assign(schema, {
      $id: options.id,
      title: options.title,
      description: options.description,
    });
    const schemaPath = resolve(generated, options.schemaName);
    const swiftOutput = resolve(
      repositoryRoot,
      "apps/apple/Packages/HitSlopApple/Sources/HitSlopCore/Generated",
      options.swiftName,
    );
    const swiftSchema = resolve(
      repositoryRoot,
      "apps/apple/Packages/HitSlopApple/Sources/HitSlopCore/Resources/manifest.schema.json",
    );
    const publicSchema = resolve(
      repositoryRoot,
      "apps/cloudflare/public/schemas/v1/manifest.schema.json",
    );
    await mkdir(resolve(swiftOutput, ".."), { recursive: true });
    await mkdir(resolve(swiftSchema, ".."), { recursive: true });
    await mkdir(resolve(publicSchema, ".."), { recursive: true });
    const serialized = `${JSON.stringify(schema, null, 2)}\n`;
    await writeFile(schemaPath, serialized);
    await writeFile(swiftSchema, serialized);
    await writeFile(publicSchema, serialized);
    const input = new JSONSchemaInput(new FetchingJSONSchemaStore());
    await input.addSource({ name: options.title, schema: serialized });
    const inputData = new InputData();
    inputData.addInput(input);
    const result = await quicktype({
      inputData,
      lang: "swift",
      rendererOptions: { "access-level": "public", sendable: "true", initializers: "false" },
    });
    // Catalog enumeration is app-specific; synthesize in the same file as the enum.
    await writeFile(
      swiftOutput,
      "// Generated by bun run schema:generate. Do not edit.\n" +
        result.lines.join("\n") +
        "\n\nextension SlopCategory: CaseIterable {}\n",
    );
  }
}
