/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiArtifactRouteImport } from './routes/api.artifact'
import { Route as ApiCatalogRouteImport } from './routes/api.catalog'
import { Route as ApiPublishRouteImport } from './routes/api.publish'
import { Route as ApiDownloadReleaseIdRouteImport } from './routes/api.download.$releaseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArtifactRoute = ApiArtifactRouteImport.update({
  id: '/api/artifact',
  path: '/api/artifact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogRoute = ApiCatalogRouteImport.update({
  id: '/api/catalog',
  path: '/api/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublishRoute = ApiPublishRouteImport.update({
  id: '/api/publish',
  path: '/api/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadReleaseIdRoute = ApiDownloadReleaseIdRouteImport.update({
  id: '/api/download/$releaseId',
  path: '/api/download/$releaseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/artifact': typeof ApiArtifactRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/publish': typeof ApiPublishRoute
  '/api/download/$releaseId': typeof ApiDownloadReleaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/artifact': typeof ApiArtifactRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/publish': typeof ApiPublishRoute
  '/api/download/$releaseId': typeof ApiDownloadReleaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/artifact': typeof ApiArtifactRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/publish': typeof ApiPublishRoute
  '/api/download/$releaseId': typeof ApiDownloadReleaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/artifact'
    | '/api/catalog'
    | '/api/publish'
    | '/api/download/$releaseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/artifact'
    | '/api/catalog'
    | '/api/publish'
    | '/api/download/$releaseId'
  id:
    | '__root__'
    | '/'
    | '/api/artifact'
    | '/api/catalog'
    | '/api/publish'
    | '/api/download/$releaseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiArtifactRoute: typeof ApiArtifactRoute
  ApiCatalogRoute: typeof ApiCatalogRoute
  ApiPublishRoute: typeof ApiPublishRoute
  ApiDownloadReleaseIdRoute: typeof ApiDownloadReleaseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/artifact': {
      id: '/api/artifact'
      path: '/api/artifact'
      fullPath: '/api/artifact'
      preLoaderRoute: typeof ApiArtifactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog': {
      id: '/api/catalog'
      path: '/api/catalog'
      fullPath: '/api/catalog'
      preLoaderRoute: typeof ApiCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/publish': {
      id: '/api/publish'
      path: '/api/publish'
      fullPath: '/api/publish'
      preLoaderRoute: typeof ApiPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download/$releaseId': {
      id: '/api/download/$releaseId'
      path: '/api/download/$releaseId'
      fullPath: '/api/download/$releaseId'
      preLoaderRoute: typeof ApiDownloadReleaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiArtifactRoute: ApiArtifactRoute,
  ApiCatalogRoute: ApiCatalogRoute,
  ApiPublishRoute: ApiPublishRoute,
  ApiDownloadReleaseIdRoute: ApiDownloadReleaseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
