import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { repository } from "../v1/runtime-artifacts";
import { output } from "./common";
const [label, ...command] = process.argv.slice(2);
if (!label || !/^[a-z0-9-]+$/.test(label) || !command.length) throw new Error("Expected label and command");
const evidence = join(repository, ".hitslop/v1-evidence/nx-pilot");
await mkdir(evidence, { recursive: true });
const before = await readFile(join(output, "executions.jsonl"), "utf8").catch(() => "");
const started = performance.now();
const child = Bun.spawn(command, { stdout: "pipe", stderr: "pipe" });
const [stdout, stderr, code] = await Promise.all([new Response(child.stdout).text(), new Response(child.stderr).text(), child.exited]);
const milliseconds = performance.now() - started;
process.stdout.write(stdout);
process.stderr.write(stderr);
const after = await readFile(join(output, "executions.jsonl"), "utf8").catch(() => "");
const executions = after.slice(before.length).trim().split("\n").filter(Boolean).map(line => JSON.parse(line));
const result = { label, milliseconds, code, executions, node: Bun.spawnSync(["node", "--version"]).stdout.toString().trim(), bun: Bun.version, platform: process.platform, arch: process.arch };
await writeFile(join(evidence, `${label}.json`), JSON.stringify(result, null, 2) + "\n");
await writeFile(join(evidence, `${label}.log`), stdout + stderr);
console.log(JSON.stringify(result));
process.exit(code);
