import { defineTheme } from "@hitslop/runtime/theme";

export default defineTheme({
  wood: "#284bd8",
  woodHi: "#3a5fed",
  woodDeep: "#1b34a0",
  brass: "#3659df",
  brassDeep: "#203ab5",
  brassHi: "#a9baff",
  card: "#ffffff",
  cardLine: "#d8e2ff",
  cardWash: "#f4f7ff",
  margin: "#284bd8",
  ink: "#19295b",
  inkMuted: "#596887",
  ivory: "#ffffff",
  focus: "#203ab5",
  again: "#ffe3d8",
  good: "#b9f4db",
  danger: "#ffd5d8",
  overlay: "rgba(14, 25, 70, 0.65)",
  answer: "#e6f0ff",
  headingFont: '"Flashcard Outfit", "Avenir Next", sans-serif',
  font: '"Avenir Next", "Helvetica Neue", Georgia, serif',
});
