import { globalStyle, style } from "@vanilla-extract/css";
import theme from "../theme";

const t = theme.vars;

globalStyle("*", { boxSizing: "border-box" });
globalStyle(":root", { fontFamily: t.font, colorScheme: "light", fontSynthesis: "none" });
globalStyle("html, body, #app", { margin: 0, minHeight: "100%", width: "100%" });
globalStyle("body", { background: t.surface, color: t.ink });
globalStyle("button, input, textarea", { font: "inherit", color: "inherit" });
globalStyle("button", { cursor: "pointer" });
globalStyle("button:disabled", { cursor: "default", opacity: .45 });
globalStyle("button:focus-visible, input:focus-visible, textarea:focus-visible", { outline: `2px solid ${t.accent}`, outlineOffset: 3 });
globalStyle("textarea", { resize: "none", overflow: "hidden" });
globalStyle("button", { WebkitTapHighlightColor: "transparent" });
export const shell = style({ position: "relative", height: "100vh", overflow: "hidden", padding: "23px 22px 18px", background: `radial-gradient(circle at 92% 18%, #ffffff1f 0 4px, transparent 5px), linear-gradient(145deg, #ffffff19, transparent 65%), ${t.surface}`, containerType: "inline-size", "@media": { "(max-width: 360px)": { padding: "18px 12px" } } });
export const header = style({ display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12, marginBottom: 24 });
export const brand = style({ display: "flex", alignItems: "center", gap: 7, fontSize: 13, fontWeight: 750 });
export const edition = style({ fontSize: 8, letterSpacing: ".12em", fontWeight: 700, "@container": { "(max-width: 350px)": { maxWidth: 70, textAlign: "right", lineHeight: 1.5 } } });
export const paper = style({ height: "calc(100vh - 80px)", minHeight: 0, display: "grid", gridTemplateRows: "auto auto auto minmax(0, 1fr) auto", border: `3px solid ${t.ink}`, borderRadius: "19px 19px 47px 19px", background: t.paper, boxShadow: `7px 8px 0 color-mix(in srgb, ${t.ink} 22%, transparent)`, overflow: "hidden" });
export const heading = style({ padding: "25px 23px 0", "@container": { "(max-width: 350px)": { padding: "22px 17px 0" } } });
export const eyebrow = style({ margin: "0 0 9px", fontSize: 12, color: t.muted });
export const title = style({ display: "block", width: "100%", minWidth: 0, border: 0, padding: 0, margin: 0, background: "transparent", fontFamily: t.headingFont, fontSize: 34, lineHeight: 1.12, letterSpacing: "-.045em", fontWeight: 400 });
export const progress = style({ display: "flex", flexWrap: "wrap", justifyContent: "space-between", gap: 8, margin: "17px 0 8px", fontSize: 11, color: t.muted, fontVariantNumeric: "tabular-nums" });
globalStyle(`${progress} > span:first-child`, { color: t.accent, fontWeight: 700 });
export const track = style({ height: 4, borderRadius: 3, background: t.control, marginBottom: 6, overflow: "hidden" });
globalStyle(`${track} > div`, { height: "100%", width: "100%", transformOrigin: "left center", background: t.success });
export const composer = style({ display: "grid", gridTemplateColumns: "1fr 42px", gap: 9, alignItems: "center", margin: "12px 20px 8px", padding: "5px 5px 5px 14px", border: 0, borderRadius: 12, background: t.control, boxShadow: `inset 0 0 0 1px ${t.controlBorder}`, "@container": { "(max-width: 350px)": { marginInline: 14 } } });
globalStyle(`${composer} input`, { minWidth: 0, width: "100%", background: "transparent", border: 0, padding: "7px 0", fontSize: 13 });
globalStyle(`${composer} input::placeholder`, { color: t.muted });
globalStyle(`${composer} button`, { display: "grid", placeItems: "center", width: 36, height: 36, border: `2px solid ${t.ink}`, borderRadius: 9, color: t.ink, background: t.highlight, boxShadow: `2px 2px 0 color-mix(in srgb, ${t.ink} 22%, transparent)` });
export const tabs = style({ display: "flex", gap: 4, padding: "5px 20px 7px", borderBottom: `1px solid ${t.rule}`, "@container": { "(max-width: 350px)": { paddingInline: 14 } } });
export const tab = style({ display: "flex", alignItems: "center", gap: 6, border: 0, borderRadius: 7, padding: "7px 9px", background: "transparent", color: t.muted, fontSize: 11, fontWeight: 750, selectors: { '&[data-state="active"]': { color: t.ink, background: t.highlight } } });
globalStyle(`${tab} span`, { minWidth: 15, textAlign: "center", fontVariantNumeric: "tabular-nums" });
export const scroller = style({ minHeight: 0, overflowY: "auto", overscrollBehavior: "contain", scrollbarWidth: "thin" });
export const filedView = style({ background: t.filed });
export const list = style({ listStyle: "none", padding: "0 20px", margin: 0, "@container": { "(max-width: 350px)": { padding: "0 14px" } } });
export const row = style({ display: "grid", gridTemplateColumns: "25px minmax(0, 1fr) 28px", alignItems: "start", gap: 11, padding: "17px 0", borderBottom: `1px solid ${t.rule}` });
globalStyle(`${row} [data-checkbox-root]`, { display: "grid", placeItems: "center", width: 24, height: 24, padding: 0, border: `1.5px solid color-mix(in srgb, ${t.muted} 65%, transparent)`, borderRadius: 7, background: "transparent", color: t.onAccent });
globalStyle(`${row} [data-state="checked"]`, { borderColor: t.successBorder, background: t.success });
export const taskText = style({ width: "100%", minHeight: 24, padding: 0, margin: 0, border: 0, background: "transparent", fontSize: 14, lineHeight: "24px", overflowWrap: "anywhere" });
globalStyle(`${row}[data-done="true"] textarea, ${row}[data-done="true"] > span`, { color: t.muted, textDecoration: "line-through", textDecorationColor: t.muted });
export const more = style({ width: 28, height: 28, marginTop: -2, display: "grid", placeItems: "center", padding: 0, border: 0, borderRadius: 5, background: "transparent", color: t.muted, selectors: { "&:hover": { background: t.control, color: t.ink } } });
export const menu = style({ minWidth: 155, padding: 5, border: `1px solid ${t.rule}`, borderRadius: 9, background: t.paper, color: t.ink, boxShadow: `0 8px 24px color-mix(in srgb, ${t.ink} 15%, transparent)`, zIndex: 20 });
globalStyle(`${menu} [data-dropdown-menu-item]`, { padding: "9px 12px", borderRadius: 5, fontSize: 13, cursor: "pointer", outline: "none" });
globalStyle(`${menu} [data-highlighted]`, { background: t.control });
globalStyle(`${menu} [data-disabled]`, { opacity: .4, cursor: "default" });
globalStyle(`${menu} [data-dropdown-menu-separator]`, { height: 1, margin: "4px 7px", background: t.rule });
export const paperFoot = style({ display: "flex", flexWrap: "wrap", justifyContent: "space-between", gap: 10, alignItems: "center", padding: "11px 20px", borderTop: `1px dashed ${t.rule}`, background: t.paper });
globalStyle(`${paperFoot} > span`, { fontSize: 10, color: t.muted });
globalStyle(`${paperFoot} button`, { display: "flex", alignItems: "center", gap: 6, border: `2px solid ${t.ink}`, borderRadius: 7, padding: "7px 9px", background: t.highlight, color: t.ink, boxShadow: `2px 2px 0 color-mix(in srgb, ${t.ink} 18%, transparent)`, fontSize: 11, fontWeight: 800 });
export const filedList = style({ padding: "0 20px", "@container": { "(max-width: 350px)": { paddingInline: 14 } } });
export const filedRow = style({ display: "flex", gap: 12, alignItems: "center", padding: "15px 0", borderBottom: `1px solid color-mix(in srgb, ${t.ink} 15%, transparent)` });
globalStyle(`${filedRow} > span`, { flex: 1, overflowWrap: "anywhere", minWidth: 0 });
globalStyle(`${filedRow} button`, { display: "flex", gap: 5, alignItems: "center", border: `1px solid ${t.ink}`, borderRadius: 6, padding: "5px 7px", background: t.success, fontSize: 11 });
export const notice = style({ position: "absolute", right: 28, bottom: 26, zIndex: 30, display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12, minWidth: 180, padding: "10px 12px", border: `2px solid ${t.ink}`, borderRadius: 8, background: t.highlight, boxShadow: `3px 3px 0 color-mix(in srgb, ${t.ink} 20%, transparent)`, fontSize: 12 });
globalStyle(`${notice} button`, { border: 0, padding: "5px 7px", borderRadius: 5, background: t.paper, color: t.accent, fontWeight: 700 });
export const empty = style({ display: "grid", justifyItems: "center", padding: "32px 20px 16px", textAlign: "center", color: t.muted });
globalStyle(`${empty} h2`, { margin: "14px 0 5px", color: t.ink, fontFamily: t.headingFont, fontSize: 23, fontWeight: 400 });
globalStyle(`${empty} p`, { margin: 0, fontSize: 12 });
export const error = style({ fontSize: 13, padding: 12, borderRadius: 8, background: t.paper, color: t.accent, overflowWrap: "anywhere" });
globalStyle('html[data-slop-capture="static"] [data-slop-export="hide"]', { display: "none !important" });
globalStyle(`html[data-slop-capture="static"] .${shell}`, { height: "auto", minHeight: "100vh", overflow: "visible" });
globalStyle(`html[data-slop-capture="static"] .${row}`, { gridTemplateColumns: "25px minmax(0, 1fr)" });
globalStyle(`html[data-slop-capture="static"] .${paper}`, { height: "auto", minHeight: 0, display: "block" });
globalStyle(`html[data-slop-capture="static"] .${scroller}`, { overflow: "visible" });
globalStyle(`html[data-slop-capture="static"] .${list}`, { paddingBottom: 28 });
export const iconTile = style({ width: 456, height: 456, borderRadius: "65px 65px 110px 65px", background: t.surface, padding: "54px 43px", boxShadow: `inset 0 0 0 4px color-mix(in srgb, ${t.ink} 20%, transparent)` });
export const iconPaper = style({ background: t.paper, borderRadius: "16px 16px 38px 16px", padding: "40px 30px", display: "grid", gap: 30, boxShadow: `0 5px 0 color-mix(in srgb, ${t.ink} 13%, transparent)` });
globalStyle(`${iconPaper} > div`, { display: "flex", gap: 20, alignItems: "center" });
globalStyle(`${iconPaper} span`, { display: "grid", placeItems: "center", width: 45, height: 45, border: `3px solid ${t.accent}`, borderRadius: 12, color: t.onAccent });
globalStyle(`${iconPaper} > div[data-complete="true"] span`, { background: t.accent });
globalStyle(`${iconPaper} i`, { height: 10, width: 165, borderRadius: 5, background: t.rule });
globalStyle(`${iconPaper} > div[data-complete="true"] i`, { background: t.muted });
globalStyle("*, *::before, *::after", { "@media": { "(prefers-reduced-motion: reduce)": { transitionDuration: "0s !important", animationDuration: "0s !important", scrollBehavior: "auto" } } });
