// Generated by bun run schema:generate. Do not edit.
import Foundation

let slopProtocolVersion = 1
let slopRoomProtocolVersion = 3
let slopRetryWindowMilliseconds = 604800000
enum SlopBridgeMethod: String, CaseIterable, Sendable {
    case hostInfo = "host.info"
    case runtimeReportError = "runtime.reportError"
    case log = "log"
    case ready = "ready"
    case documentOpen = "document.open"
    case documentExecute = "document.execute"
    case documentFlush = "document.flush"
    case mediaOpen = "media.open"
    case mediaAdd = "media.add"
    case windowResize = "window.resize"
}
enum SlopBridgeErrorCode: String, Sendable {
    case invalidRequest = "invalid_request"
    case unsupported = "unsupported"
    case validationFailed = "validation_failed"
    case storageError = "storage_error"
    case limitExceeded = "limit_exceeded"
    case closed = "closed"
}
