import { expect, test } from "bun:test";
import { access, mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { assistantIdentity, attributionLines, inspectCommits, protectedPullBase } from "../../scripts/ci/attribution";
import { run } from "../../scripts/lib/test-process";

test("attribution checks development and release PRs", () => {
  for (const base of ["master", "release/1.0", "release/2.1"]) expect(protectedPullBase(base)).toBe(true);
  for (const base of ["feature/foo", "release", "release/", "release/1.0/extra"]) expect(protectedPullBase(base)).toBe(false);
});

test("recognizes assistant credit without rejecting human collaborators or prose", () => {
  for (const identity of [
    "Claude <noreply@anthropic.com>", "Claude Opus 5.5 <bot@example.invalid>",
    "Codex <bot@example.invalid>", "GitHub Copilot <bot@example.invalid>",
    "Cursor <bot@example.invalid>", "ChatGPT <bot@example.invalid>",
    "Gemini CLI <bot@example.invalid>", "Aider <bot@example.invalid>",
    "Devin <bot@example.invalid>", "OpenHands <bot@example.invalid>",
    "OpenCode <bot@example.invalid>", "Amp <bot@example.invalid>",
    "Assistant <123+copilot-swe-agent[bot]@users.noreply.github.com>",
  ]) expect(attributionLines(`cO-AuThOrEd-By: ${identity}\r\n`, "commit")).toHaveLength(1);
  for (const text of [
    "Co-authored-by: Claude Shannon <claude@example.com>",
    "Co-authored-by: Claude <claude@example.com>",
    "Co-authored-by: Jane Engineer <jane@openai.com>",
    "Co-authored-by: Jane Engineer <jane@anthropic.com>",
    "Fix the Claude integration and document how Copilot works.",
    "Generated with Python", "Discuss Co-authored-by trailers and AI tooling",
  ]) expect(attributionLines(text, "PR description")).toEqual([]);
  expect(assistantIdentity("Jordan", "jordan@example.com")).toBe(false);
});

test("recognizes generated signatures, Markdown links and session trailers", () => {
  for (const signature of [
    "🤖 Generated with [Claude Code](https://claude.ai)", "Generated with Cursor",
    "**Generated by OpenAI Codex**", "Written using GitHub Copilot",
    "Generated with Gemini CLI", "Generated by an AI assistant", "🤖 Generated with SomeNewAgent",
    "Claude-Session: https://claude.ai/code/session_123",
  ]) expect(attributionLines(`Description\n\n${signature}`, "PR description")).toHaveLength(1);
});

test("inspects all incoming commits including older and merged credit without executing their code", async () => {
  const root = await mkdtemp(join(tmpdir(), "attribution-"));
  const git = (...args: string[]) => run(["git", ...args], { cwd: root });
  const commit = async (parent: string | undefined, message: string) => (await git(
    "-c", "user.name=Test Human", "-c", "user.email=human@example.invalid",
    "-c", "commit.gpgsign=false", "commit-tree", tree, ...(parent ? ["-p", parent] : []), "-m", message,
  )).trim();
  let tree = "";
  try {
    await git("init", "-q");
    tree = (await git("mktree")).trim();
    const base = await commit(undefined, "Existing history\n\nCo-authored-by: Claude <noreply@anthropic.com>");
    await mkdir(join(root, "scripts/ci"), { recursive: true });
    await writeFile(join(root, "scripts/ci/attribution.ts"), 'await Bun.write("executed", "PR code ran");\n');
    await git("add", "scripts/ci/attribution.ts");
    tree = (await git("write-tree")).trim();
    const flagged = await commit(base, "Earlier change\n\nCo-authored-by: Claude <noreply@anthropic.com>");
    let head = flagged;
    // More than the PR commits API's limit: the Git walk must still find the first violation.
    for (let i = 0; i < 251; i++) head = await commit(head, `Clean change ${i}`);
    expect(await inspectCommits(root, base, head)).toEqual([{ source: flagged, line: "Co-authored-by: Claude <noreply@anthropic.com>" }]);
    const side = await commit(base, "Side branch\n\nGenerated with Cursor");
    const merge = (await git("-c", "user.name=Test Human", "-c", "user.email=human@example.invalid", "-c", "commit.gpgsign=false",
      "commit-tree", tree, "-p", head, "-p", side, "-m", "Merge the side branch")).trim();
    expect((await inspectCommits(root, base, merge)).map(f => f.source).sort()).toEqual([flagged, side].sort());
    const clean = await commit(base, "Human work\n\nCo-authored-by: Claude Shannon <claude@example.com>");
    expect(await inspectCommits(root, base, clean)).toEqual([]);
    const bot = (await git("-c", "user.name=Codex", "-c", "user.email=bot@example.invalid", "-c", "commit.gpgsign=false",
      "commit-tree", tree, "-p", base, "-m", "Clean message, assistant identity")).trim();
    expect((await inspectCommits(root, base, bot)).map(f => f.source)).toEqual([`${bot} author`, `${bot} committer`]);
    await expect(access(join(root, "executed"))).rejects.toThrow();
    await expect(inspectCommits(root, "0".repeat(40), head)).rejects.toThrow();
  } finally { await rm(root, { recursive: true, force: true }); }
}, 60_000);
