/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false --env-interface=CloudflareEnv` (hash: f00e9af89c94c0f2e2355e40741b1047)
interface __BaseEnv_CloudflareEnv {
	ARTIFACTS: R2Bucket;
	ENVIRONMENT: "production" | "development";
	CONVEX_URL: "https://fastidious-malamute-777.convex.cloud" | "https://giddy-opossum-593.convex.cloud";
	CONVEX_SITE_URL: "https://fastidious-malamute-777.convex.site" | "https://giddy-opossum-593.convex.site";
	HITSLOP_INTERNAL_SECRET: string;
}
declare namespace Cloudflare {
	interface ProductionEnv {
		ARTIFACTS: R2Bucket;
		ENVIRONMENT: "production";
		CONVEX_URL: "https://fastidious-malamute-777.convex.cloud";
		CONVEX_SITE_URL: "https://fastidious-malamute-777.convex.site";
		HITSLOP_INTERNAL_SECRET: string;
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "CONVEX_URL" | "CONVEX_SITE_URL" | "HITSLOP_INTERNAL_SECRET">> {}
}
