// Generated by bun run schema:generate. Do not edit.
import Foundation

let slopProtocolVersion = 1
enum SlopBridgeMethod: String, CaseIterable, Sendable {
    case hostInfo = "host.info"
    case log = "log"
    case ready = "ready"
    case syncOpen = "sync.open"
    case syncCommit = "sync.commit"
    case syncReadExternal = "sync.readExternal"
    case syncReview = "sync.review"
    case errorsReport = "errors.report"
    case errorsClear = "errors.clear"
    case mediaOpen = "media.open"
    case mediaWrite = "media.write"
    case mediaRemove = "media.remove"
    case windowResize = "window.resize"
    case windowDrag = "window.drag"
}
enum SlopBridgeErrorCode: String, Sendable {
    case invalidRequest = "invalid_request"
    case unsupported = "unsupported"
    case revisionConflict = "revision_conflict"
    case validationFailed = "validation_failed"
    case storageError = "storage_error"
    case limitExceeded = "limit_exceeded"
    case closed = "closed"
}
