import { mkdir, readFile, readdir, writeFile, mkdtemp, rename, rm } from "node:fs/promises";
import { join, resolve } from "node:path";
import { build, createServer, type Plugin } from "vite";
import { parseManifest, manifestSchemaURL } from "@hitslop/schema";
import { minimumRuntimeVersion } from "@hitslop/schema/document-runtime";
import type { CollectionSchema } from "@hitslop/schema/collections";
import { evaluateModule } from "./evaluate-module.ts";
import { loadAuthoringManifest } from "./project.ts";
import { hitSlopBuildPlugin } from "./vite-build-plugin.ts";
import { readThemeCSS } from "./theme.ts";
import { themePreviewPlugin } from "./dev.ts";

const repository = resolve(import.meta.dir, "../../..");
const native = resolve(repository, "apps/apple/Packages/HitSlopApple/.build/debug/hitslop-collections-spike");
export async function collectionsNative(args: string[]) {
  const p = Bun.spawn([native, ...args], { stdout: "pipe", stderr: "pipe" });
  const [output, error, code] = await Promise.all([new Response(p.stdout).text(), new Response(p.stderr).text(), p.exited]);
  if (code) throw new Error(error.trim()); return output.trim();
}
function typeOf(s: any): string { if (s.const !== undefined) return JSON.stringify(s.const); if (s.enum) return s.enum.map(JSON.stringify).join(" | "); return s.type === "integer" ? "number" : s.type; }
export async function generateCollections(root: string): Promise<CollectionSchema> {
  const schema = await evaluateModule(join(root, "schema.ts"), "schema") as CollectionSchema;
  if (schema?.format !== "hitslop-collections-1" || !schema.collections || !schema.document) throw new Error("Expected experimental defineSchema");
  const models = Object.entries(schema.collections).map(([name, c]) => `  ${JSON.stringify(name)}: { ${Object.entries(c.fields).map(([field, s]) => `${JSON.stringify(field)}: ${typeOf(s)}`).join("; ")} };`).join("\n");
  const api = Object.keys(schema.collections).map(name => `  ${JSON.stringify(name)}: collectionAPI<Models[${JSON.stringify(name)}], ${JSON.stringify(name)}, ${Object.keys(schema.collections[name]!.indexes).map(n => JSON.stringify(n)).join(" | ") || "never"}>(${JSON.stringify(name)}),`).join("\n");
  const files = {
    "dataModel.ts": `// Generated by slop. Do not edit.\nimport type { Id as CollectionId } from "@hitslop/schema/collections";\nexport interface Models {\n${models}\n}\nexport type Id<C extends keyof Models> = CollectionId<C>;\nexport type Doc<C extends keyof Models> = Models[C] & { _id: Id<C> };\n`,
    "api.ts": `// Generated by slop. Do not edit.\nimport { collectionAPI } from "@hitslop/schema/collections";\nimport type { Models } from "./dataModel";\nexport const api = {\n${api}\n};\n`,
    "schema.json": JSON.stringify(schema, null, 2) + "\n",
  };
  await mkdir(join(root, "_generated"), { recursive: true });
  for (const [name, text] of Object.entries(files)) {
    const path = join(root, "_generated", name);
    if (await readFile(path, "utf8").catch(() => "") !== text) await writeFile(path, text);
  }
  return schema;
}
export function collectionCodegen(root: string, preview: boolean): Plugin {
  root = resolve(root); let schema: CollectionSchema;
  return { name: "hitslop-experimental-collections", enforce: "pre",
    async buildStart() { schema = await generateCollections(root); },
    async handleHotUpdate(ctx) {
      if (ctx.file.startsWith(root + "/") && !ctx.file.includes("/_generated/") && /\.(ts|js)$/.test(ctx.file)) {
        try { schema = await generateCollections(root); ctx.server.ws.send({ type: "full-reload" }); }
        catch (e) { ctx.server.ws.send({ type: "error", err: { message: String(e), stack: "" } }); }
      }
    },
    transform(code, id) { if (preview && id === join(root, "src/main.ts")) return 'import "virtual:collections-preview";\n' + code; },
    resolveId(id) { if (id === "virtual:collections-preview") return "\0" + id; },
    load(id) { if (id === "\0virtual:collections-preview") return `import { installPreview } from ${JSON.stringify(join(import.meta.dir, "collections-preview.ts"))}; installPreview(${JSON.stringify(schema)});`; },
  };
}
export async function devCollections(root: string) {
  await loadAuthoringManifest(root); await generateCollections(root);
  const server = await createServer({ root, server: { host: "127.0.0.1", port: 5198, strictPort: true }, plugins: [collectionCodegen(root, true), themePreviewPlugin(root)] });
  await server.listen(); console.log(`Experimental collections preview: ${server.resolvedUrls?.local[0]}`);
}
export async function buildCollections(root: string) {
  root = resolve(root); const authored = await loadAuthoringManifest(root); const schema = await generateCollections(root);
  const dist = join(root, "dist"); await mkdir(dist, { recursive: true });
  const staging = await mkdtemp(join(dist, ".collections-")), output = join(dist, `${authored.slug}.slopsql`);
  try {
    const assets = join(staging, "runtime"), theme = await readThemeCSS(root);
    await build({ root, plugins: [collectionCodegen(root, false), hitSlopBuildPlugin({ hasTheme: false })], build: { outDir: assets, emptyOutDir: true } });
    await rename(join(assets, "index.html"), join(assets, "app.html"));
    if (theme) { await mkdir(join(assets, "assets"), { recursive: true }); await writeFile(join(assets, "assets/theme.css"), theme); }
    await writeFile(join(assets, "manifest.json"), JSON.stringify(parseManifest({ ...authored, $schema: manifestSchemaURL, runtime: minimumRuntimeVersion }), null, 2));
    await writeFile(join(assets, "collections.schema.json"), JSON.stringify(schema, null, 2) + "\n");
    await writeFile(join(assets, "data.schema.json"), JSON.stringify(schema.document, null, 2));
    await writeFile(join(assets, "collections.api.json"), JSON.stringify({ format: 1, operations: ["insert", "find", "findOne", "update", "delete", "count"], collections: Object.keys(schema.collections), guide: "collections-guide.md" }, null, 2));
    await writeFile(join(assets, "collections-guide.md"), '# Experimental collection document\n\nUse `slop inspect FILE` for schema and `slop collections OP FILE COLLECTION --args JSON` for data. Close the document before CLI mutations. Find accepts equality `where`, a declared `index`, `order`, `limit` (1–200), and `cursor`; it returns `{items,nextCursor}`. findOne/update/delete require an explicit `id`. update also takes `changes`. insert takes all declared fields and returns a host UUID. count accepts `where`. Records and indexes are readable with SQLite; writes must use the host or CLI to update Loro and the outbox atomically. Code and schema are immutable; rebuild the authoring project to change them. This lab has no schema migration or media API.\n');
    for (const file of await readdir(assets)) if (!["app.html", "assets", "manifest.json", "collections.schema.json", "data.schema.json", "collections.api.json", "collections-guide.md"].includes(file)) throw new Error(`Unexpected runtime output: ${file}`);
    const packed = join(staging, "document.slopsql"); await collectionsNative(["pack", assets, packed]);
    await rename(packed, output); return output;
  } finally { await rm(staging, { recursive: true, force: true }); }
}
