import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { quicktype, InputData, JSONSchemaInput, FetchingJSONSchemaStore } from "quicktype-core";
import { SlopManifestSchema } from "../packages/schema/src/index";
import { SlopCategories, WindowBounds, AttachmentLimits, base64Length, StorageLimits, ThemeLimit, ErrorTextLimit, PagePayloadLimit, PushLimits, SocketLimits } from "../packages/schema/src/constants";
import { rustOwnerWire } from "./rust-contracts";
import { OwnerContractsSchema, CoreErrorCodes, PageErrorCodes } from "../packages/schema/src/owner";
import { swiftContracts } from "./swift-contracts";
import { BridgeMethods, BridgeRequestSchema } from "../packages/schema/src/bridge";
import {
  SocketRequestSchema,
  SocketReplySchema,
  SocketDiscoverySchema,
} from "../packages/schema/src/socket";
const root = resolve(import.meta.dir, "..");
export async function generateContracts(check = false) {
  const schema = JSON.stringify(SlopManifestSchema, null, 2) + "\n";
  const input = new JSONSchemaInput(new FetchingJSONSchemaStore());
  await input.addSource({ name: "SlopManifest", schema });
  const inputData = new InputData();
  inputData.addInput(input);
  const result = await quicktype({
    inputData,
    lang: "swift",
    rendererOptions: { "access-level": "public", sendable: "true" },
  });
  const outputs = {
    "apps/apple/Packages/HitSlopApple/Sources/HitSlopCore/Generated/Constants.generated.swift":
      `// Generated by bun run schema:generate. Do not edit.
public enum AttachmentLimits {
  public static let file = ${AttachmentLimits.file}
  public static let total = ${AttachmentLimits.total}
  public static let count = ${AttachmentLimits.count}
  /// The longest file name and MIME type a reference keeps, in UTF-8 bytes.
  public static let name = ${AttachmentLimits.name}
  public static let encodedFile = ${base64Length(AttachmentLimits.file)}
}
extension SlopCategory {
  /// The manifest schema's order, which the catalog lists categories in.
  public static let schemaOrder: [SlopCategory] = [${SlopCategories.map((c) => `SlopCategory(rawValue: "${c}")!`).join(", ")}]
}
public enum WindowBounds {
  public static let minWidth = ${WindowBounds.minWidth}
  public static let minHeight = ${WindowBounds.minHeight}
  public static let max = ${WindowBounds.max}
}
public enum Limits {
  /// A page request payload (a batch or text edit), in UTF-8 bytes.
  public static let pagePayload = ${PagePayloadLimit}
  /// A document's saved checkpoint plus updates, in bytes, and its update rows.
  public static let storageBytes = ${StorageLimits.bytes}
  public static let storageRows = ${StorageLimits.rows}
  /// Effective theme JSON, in UTF-8 bytes.
  public static let theme = ${ThemeLimit}
  /// Diagnostic text a page reports, in UTF-16 units.
  public static let errorText = ${ErrorTextLimit}
  /// Pushes buffered for one page before a gap forces a fresh snapshot.
  public static let pushItems = ${PushLimits.items}
  public static let pushBytes = ${PushLimits.bytes}
  /// Socket requests: every method, and attachment uploads.
  public static let socketRequest = ${SocketLimits.request}
  public static let socketAttachment = ${SocketLimits.attachment}
}
`,
    "crates/hitslop-core/src/wire.generated.rs": rustOwnerWire,
    "packages/schema/generated/owner.schema.json":
      JSON.stringify(OwnerContractsSchema, null, 2) + "\n",
    "apps/apple/Packages/HitSlopApple/Sources/HitSlopCore/Generated/Owner.generated.swift":
      "// Generated by bun run schema:generate. Do not edit.\nimport Foundation\n" +
      `public enum CoreErrorCode: String, Codable, Sendable {\n${CoreErrorCodes.map(code => `  case ${code}`).join("\n")}\n}\n` +
      `public enum PageErrorCode: String, Sendable {\n${PageErrorCodes.map(code => `  case ${code}`).join("\n")}\n}\n`,
    "packages/schema/generated/socket-request.schema.json":
      JSON.stringify(SocketRequestSchema, null, 2) + "\n",
    "packages/schema/generated/socket-reply.schema.json":
      JSON.stringify(SocketReplySchema, null, 2) + "\n",
    "packages/schema/generated/socket-discovery.schema.json":
      JSON.stringify(SocketDiscoverySchema, null, 2) + "\n",
    "packages/schema/generated/manifest.schema.json": schema,
    "packages/schema/generated/bridge.schema.json":
      JSON.stringify(BridgeRequestSchema, null, 2) + "\n",
    "apps/apple/Packages/HitSlopApple/Sources/HitSlopCore/Generated/SlopManifest.generated.swift":
      "// Generated by bun run schema:generate. Do not edit.\n" +
      result.lines.join("\n").trimEnd() +
      "\n\nextension SlopCategory: CaseIterable {}\n",
    "apps/apple/Packages/HitSlopApple/Sources/HitSlopCore/Generated/Contracts.generated.swift":
      swiftContracts(
        SocketRequestSchema,
        SocketReplySchema,
        SocketDiscoverySchema,
        Object.keys(BridgeMethods),
      ),
  };
  for (const [name, value] of Object.entries(outputs)) {
    const path = resolve(root, name);
    if (check) {
      if ((await readFile(path, "utf8")) !== value) throw new Error(`Generated drift: ${name}`);
    } else {
      await mkdir(dirname(path), { recursive: true });
      await writeFile(path, value);
    }
  }
}

if (import.meta.main) await generateContracts(process.argv.includes("--check"));
