import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { quicktype, InputData, JSONSchemaInput, FetchingJSONSchemaStore } from "quicktype-core";
import { SlopManifestSchema } from "../packages/schema/src/index";
import { SlopCategories, WindowBounds, AttachmentLimits, base64Length, StorageLimits, ThemeLimit, ThemeFileLimit, ErrorTextLimit, PagePayloadLimit, PushLimits, SocketLimits, AssetLimits, PackageFormat, RuntimeABI, HelperProtocol } from "../packages/schema/src/constants";
import { rustOwnerWire } from "./rust-contracts";
import { swiftContracts } from "./swift-contracts";
import { PageFailureSchema, PageRequestSchema, PageResults } from "../packages/schema/src/page";
import {
  SocketRequestSchema,
  SocketReplySchema,
  SocketDiscoverySchema,
} from "../packages/schema/src/socket";
const root = resolve(import.meta.dir, "..");
export async function generateContracts(check = false) {
  // A document stores the authored manifest; its package format and runtime ABI are
  // columns beside it, so Swift's model and the core's validator use the authored schema.
  const schema = JSON.stringify(SlopManifestSchema, null, 2) + "\n";
  const input = new JSONSchemaInput(new FetchingJSONSchemaStore());
  await input.addSource({ name: "SlopManifest", schema });
  const inputData = new InputData();
  inputData.addInput(input);
  const result = await quicktype({
    inputData,
    lang: "swift",
    rendererOptions: { "access-level": "public", sendable: "true" },
  });
  const outputs = {
    "apps/apple/Packages/HitSlopApple/Sources/HitSlopCore/Generated/Constants.generated.swift":
      `// Generated by bun run schema:generate. Do not edit.
public enum AttachmentLimits {
  public static let file = ${AttachmentLimits.file}
  public static let total = ${AttachmentLimits.total}
  public static let count = ${AttachmentLimits.count}
  /// The longest file name and MIME type a reference keeps, in UTF-8 bytes.
  public static let name = ${AttachmentLimits.name}
  public static let encodedFile = ${base64Length(AttachmentLimits.file)}
}
extension SlopCategory {
  /// The manifest schema's order, which the catalog lists categories in.
  public static let schemaOrder: [SlopCategory] = [${SlopCategories.map((c) => `SlopCategory(rawValue: "${c}")!`).join(", ")}]
}
/// The platform level this build runs; a template or document above it needs a newer app.
public enum PackageFormat {
  public static let level = ${PackageFormat}
}
public enum RuntimeABI {
  public static let level = ${RuntimeABI}
}
/// The helper's command-line protocol: the version it speaks and the oldest it serves.
public enum HelperProtocol {
  public static let version = ${HelperProtocol.version}
  public static let minimum = ${HelperProtocol.minimum}
}
public enum WindowBounds {
  public static let minWidth = ${WindowBounds.minWidth}
  public static let minHeight = ${WindowBounds.minHeight}
  public static let max = ${WindowBounds.max}
}
public enum Limits {
  /// A page request payload (a batch or text edit), in UTF-8 bytes.
  public static let pagePayload = ${PagePayloadLimit}
  /// A document's saved checkpoint plus updates, in bytes, and its update rows.
  public static let storageBytes = ${StorageLimits.bytes}
  public static let storageRows = ${StorageLimits.rows}
  /// Effective theme JSON, and a theme file, in UTF-8 bytes.
  public static let theme = ${ThemeLimit}
  public static let themeFile = ${ThemeFileLimit}
  /// Diagnostic text a page reports, in UTF-16 units.
  public static let errorText = ${ErrorTextLimit}
  /// Pushes buffered for one page before a gap forces a fresh snapshot.
  public static let pushItems = ${PushLimits.items}
  public static let pushBytes = ${PushLimits.bytes}
  /// Socket requests: every method, and attachment uploads.
  public static let socketRequest = ${SocketLimits.request}
  public static let socketAttachment = ${SocketLimits.attachment}
  /// An app's assets: one file, the asset count and total bytes; image size.
  public static let assetFile = ${AssetLimits.file}
  public static let assetCount = ${AssetLimits.count}
  public static let assetBytes = ${AssetLimits.bytes}
  public static let imageSide = ${AssetLimits.imageSide}
  public static let imagePixels = ${AssetLimits.imagePixels}
}
`,
    "crates/hitslop-core/src/wire.generated.rs": rustOwnerWire,
    "packages/schema/generated/socket-request.schema.json":
      JSON.stringify(SocketRequestSchema, null, 2) + "\n",
    "packages/schema/generated/socket-reply.schema.json":
      JSON.stringify(SocketReplySchema, null, 2) + "\n",
    "packages/schema/generated/socket-discovery.schema.json":
      JSON.stringify(SocketDiscoverySchema, null, 2) + "\n",
    "packages/schema/generated/manifest.schema.json": schema,
    "packages/schema/generated/page-request.schema.json":
      JSON.stringify(PageRequestSchema, null, 2) + "\n",
    "apps/apple/Packages/HitSlopApple/Sources/HitSlopCore/Generated/SlopManifest.generated.swift":
      "// Generated by bun run schema:generate. Do not edit.\n" +
      result.lines.join("\n").trimEnd() +
      "\n\nextension SlopCategory: CaseIterable {}\n",
    "apps/apple/Packages/HitSlopApple/Sources/HitSlopCore/Generated/Contracts.generated.swift":
      swiftContracts(
        SocketRequestSchema,
        SocketReplySchema,
        SocketDiscoverySchema,
        PageRequestSchema,
        PageFailureSchema,
        PageResults,
      ),
  };
  for (const [name, value] of Object.entries(outputs)) {
    const path = resolve(root, name);
    if (check) {
      if ((await readFile(path, "utf8")) !== value) throw new Error(`Generated drift: ${name}`);
    } else {
      await mkdir(dirname(path), { recursive: true });
      await writeFile(path, value);
    }
  }
}

if (import.meta.main) await generateContracts(process.argv.includes("--check"));
