// Generated by bun run schema:generate. Do not edit.
use serde::{Serialize, Deserialize};
use serde_json::Value;
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Code { TypeMismatch, OutOfRange, PathNotFound, InvalidKey, Exists, DuplicateId, InvalidRequest, InvalidId, InvalidPath, InvalidSchema, TooLarge, StaleBase, InvalidVersion, InvalidBytes, MissingDependencies, EngineError, InvalidShape, RequiresUpdate, IsTemplate }
impl Code {
    pub fn as_str(self) -> &'static str { match self {
        Self::TypeMismatch => "type_mismatch",
        Self::OutOfRange => "out_of_range",
        Self::PathNotFound => "path_not_found",
        Self::InvalidKey => "invalid_key",
        Self::Exists => "exists",
        Self::DuplicateId => "duplicate_id",
        Self::InvalidRequest => "invalid_request",
        Self::InvalidId => "invalid_id",
        Self::InvalidPath => "invalid_path",
        Self::InvalidSchema => "invalid_schema",
        Self::TooLarge => "too_large",
        Self::StaleBase => "stale_base",
        Self::InvalidVersion => "invalid_version",
        Self::InvalidBytes => "invalid_bytes",
        Self::MissingDependencies => "missing_dependencies",
        Self::EngineError => "engine_error",
        Self::InvalidShape => "invalid_shape",
        Self::RequiresUpdate => "requires_update",
        Self::IsTemplate => "is_template",
    } }
}
impl std::fmt::Display for Code {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result { f.write_str(self.as_str()) }
}
/// The platform level this build runs; a template or document above it needs a newer app.
pub const PACKAGE_FORMAT: u64 = 1;
pub const RUNTIME_ABI: u64 = 1;
/// The CSS `border-radius` of a window whose manifest names no shape.
pub(crate) const DEFAULT_WINDOW_RADIUS: &str = "22px";
/// Effective theme JSON, and a theme file, in UTF-8 bytes.
pub(crate) const THEME_LIMIT: usize = 65536;
pub(crate) const THEME_FILE_LIMIT: usize = 66560;
/// The longest theme token name, the most tokens a palette declares, and the token
/// prefix the host reserves.
pub(crate) const THEME_NAME_LIMIT: usize = 64;
pub(crate) const THEME_TOKENS: usize = 256;
pub(crate) const THEME_RESERVED_PREFIX: &str = "window-";
/// The lowercase Crockford alphabet of minted and derived row IDs.
pub(crate) const ID_ALPHABET: &[u8] = b"0123456789abcdefghjkmnpqrstvwxyz";
/// A document's saved checkpoint plus updates, in bytes, and its update rows.
pub const STORAGE_BYTES: usize = 33554432;
pub const STORAGE_ROWS: usize = 4096;
/// An app: its manifest and its descriptor or initial values, in bytes, and its longest
/// asset path; one asset's bytes, the asset count and their total bytes; and the largest
/// image it may carry, per side and in pixels.
#[cfg(feature = "storage")]
pub(crate) const MANIFEST_BYTES: usize = 65536;
pub(crate) const APP_TEXT_BYTES: usize = 4194304;
#[cfg(feature = "storage")]
pub(crate) const ASSET_PATH_BYTES: usize = 240;
pub const ASSET_FILE_BYTES: usize = 26214400;
pub const ASSET_COUNT: usize = 256;
pub const ASSET_BYTES: usize = 52428800;
pub const IMAGE_SIDE: usize = 16384;
pub const IMAGE_PIXELS: usize = 24000000;
/// A document's attachments: one file's bytes, their total bytes and their count.
pub const ATTACHMENT_FILE_BYTES: usize = 10485760;
pub const ATTACHMENT_BYTES: usize = 104857600;
pub const ATTACHMENT_COUNT: usize = 256;
/// A window shape's longest path data and radius list, and its largest view box side.
pub(crate) const SHAPE_PATH: usize = 4096;
pub(crate) const SHAPE_RADIUS: usize = 256;
pub(crate) const SHAPE_VIEW_BOX: f64 = 16384.0;
/// A batch's most intents and an intent's longest path; a page request's largest payload.
pub(crate) const BATCH_INTENTS: usize = 1000;
pub(crate) const PATH_SEGMENTS: usize = 64;
pub(crate) const PAGE_PAYLOAD: usize = 4194304;
/// The largest socket request, an attachment upload; no envelope the core checks is larger.
#[cfg(feature = "storage")]
pub(crate) const SOCKET_ATTACHMENT: usize = 16777216;
/// An attachment's identity: the SHA-256 of its bytes, in lowercase hex.
#[cfg(feature = "storage")]
pub(crate) fn valid_attachment_id(id: &str) -> bool {
    id.len() == 64 && id.bytes().all(|b| b"0123456789abcdef".contains(&b))
}
pub(crate) fn valid_id(value: &str) -> bool {
    !value.is_empty() && value.len() <= 64 && value.bytes().all(|b| b"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz_-".contains(&b))
}
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(untagged, deny_unknown_fields)]
pub enum Segment {
    Key(String),
    Id { id: String },
    Index { index: usize },
}
#[derive(Debug, Deserialize)]
#[serde(untagged, deny_unknown_fields)]
pub enum Anchor {
    Before { before: String },
    After { after: String },
}
#[derive(Clone, Debug, PartialEq, Serialize)]
#[serde(untagged, deny_unknown_fields)]
pub enum Hunk {
    Retain { retain: usize },
    Insert { insert: String },
    Delete { delete: usize },
}
#[derive(Debug, Serialize)]
#[serde(tag = "type", rename_all = "camelCase")]
pub enum PatchOp {
    Set { path: Vec<Segment>, value: Value },
    Text { path: Vec<Segment>, delta: Vec<Hunk> },
    Remove { path: Vec<Segment> },
    InsertRow { path: Vec<Segment>, index: usize, value: Value },
    DeleteRow { path: Vec<Segment>, id: String },
    MoveRow { path: Vec<Segment>, id: String, index: usize },
}
impl PatchOp {
    pub fn path(&self) -> &[Segment] { match self {
        Self::Set { path, .. } => path,
        Self::Text { path, .. } => path,
        Self::Remove { path, .. } => path,
        Self::InsertRow { path, .. } => path,
        Self::DeleteRow { path, .. } => path,
        Self::MoveRow { path, .. } => path,
    } }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum IssueCode { TypeMismatch, OutOfRange, UnknownField, InvalidKey, InvalidId, DuplicateId }
#[derive(Clone, Debug, PartialEq, Serialize)]
pub struct Issue { pub code: IssueCode, pub path: Vec<Segment> }
#[derive(Debug, Serialize)]
pub struct State { pub sequence: u64, pub version: String, pub value: Value, pub issues: Vec<Issue> }
#[derive(Debug, Serialize)]
pub struct Publication { pub previous: u64, pub sequence: u64, pub version: String, pub ops: Vec<PatchOp>, #[serde(skip_serializing_if = "Option::is_none")] pub issues: Option<Vec<Issue>> }
#[derive(Debug, Deserialize)]
#[serde(tag = "type", rename_all = "lowercase", deny_unknown_fields)]
pub enum Intent {
    Set { path: Vec<Segment>, value: Value },
    Insert { path: Vec<Segment>, value: Value, id: Option<String>, at: Option<Anchor>, index: Option<usize> },
    Remove { path: Vec<Segment>, id: Option<String>, index: Option<usize>, count: Option<usize> },
    Move { path: Vec<Segment>, id: String, at: Option<Anchor> },
    Clear { path: Vec<Segment> },
    Increment { path: Vec<Segment>, by: i64 },
    Replace { path: Vec<Segment>, value: Value },
}
impl Intent {
    pub fn path(&self) -> &[Segment] { match self {
        Self::Set { path, .. } => path,
        Self::Insert { path, .. } => path,
        Self::Remove { path, .. } => path,
        Self::Move { path, .. } => path,
        Self::Clear { path, .. } => path,
        Self::Increment { path, .. } => path,
        Self::Replace { path, .. } => path,
    } }
}
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Batch { pub intents: Vec<Intent> }
/// A shared theme file: the template it was made for and its palette.
#[derive(Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ThemeFile { pub template: String, pub values: std::collections::BTreeMap<String, String> }
/// A built app (a build's `app.json`), as the file engine packs it into the `app` row.
/// Each part stays the JSON text the build wrote: its own validator reads it, in order.
#[cfg(feature = "storage")]
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
#[allow(non_snake_case)]
pub struct AppRow { pub packageFormat: u64, pub runtimeABI: u64, pub manifest: Box<serde_json::value::RawValue>, pub descriptor: Box<serde_json::value::RawValue>, pub initial: Box<serde_json::value::RawValue>, pub theme: Box<serde_json::value::RawValue> }
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
#[allow(non_snake_case)]
pub struct EditText { pub base: String, pub path: Vec<Segment>, pub from: String, pub to: String, pub selectionStart: usize, pub selectionEnd: usize }
