// Generated by bun run schema:generate. Do not edit.
use serde::{Serialize, Deserialize};
use serde_json::Value;
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Code { TypeMismatch, OutOfRange, PathNotFound, InvalidKey, Exists, DuplicateId, InvalidRequest, InvalidId, InvalidPath, InvalidSchema, TooLarge, StaleBase, InvalidVersion, InvalidBytes, MissingDependencies, EngineError, InvalidShape, RequiresUpdate, IsTemplate }
impl Code {
    pub fn as_str(self) -> &'static str { match self {
        Self::TypeMismatch => "type_mismatch",
        Self::OutOfRange => "out_of_range",
        Self::PathNotFound => "path_not_found",
        Self::InvalidKey => "invalid_key",
        Self::Exists => "exists",
        Self::DuplicateId => "duplicate_id",
        Self::InvalidRequest => "invalid_request",
        Self::InvalidId => "invalid_id",
        Self::InvalidPath => "invalid_path",
        Self::InvalidSchema => "invalid_schema",
        Self::TooLarge => "too_large",
        Self::StaleBase => "stale_base",
        Self::InvalidVersion => "invalid_version",
        Self::InvalidBytes => "invalid_bytes",
        Self::MissingDependencies => "missing_dependencies",
        Self::EngineError => "engine_error",
        Self::InvalidShape => "invalid_shape",
        Self::RequiresUpdate => "requires_update",
        Self::IsTemplate => "is_template",
    } }
}
impl std::fmt::Display for Code {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result { f.write_str(self.as_str()) }
}
/// The platform level this build runs; a template or document above it needs a newer app.
pub const PACKAGE_FORMAT: u64 = 1;
pub const RUNTIME_ABI: u64 = 1;
#[cfg(feature = "storage")]
pub const HELPER_PROTOCOL: u64 = 1;
/// The CSS `border-radius` of a window whose manifest names no shape.
pub(crate) const DEFAULT_WINDOW_RADIUS: &str = "22px";
/// Effective theme JSON, and a theme file, in UTF-8 bytes.
pub(crate) const THEME_LIMIT: usize = 65536;
pub(crate) const THEME_FILE_LIMIT: usize = 66560;
/// The longest theme token name, the most tokens a palette declares, and the token
/// prefix the host reserves.
pub(crate) const THEME_NAME_LIMIT: usize = 64;
pub(crate) const THEME_TOKENS: usize = 256;
pub(crate) const THEME_RESERVED_PREFIX: &str = "window-";
/// The lowercase Crockford alphabet of minted and derived row IDs.
pub(crate) const ID_ALPHABET: &[u8] = b"0123456789abcdefghjkmnpqrstvwxyz";
/// A document's saved checkpoint plus updates, in bytes, and its update rows.
pub const STORAGE_BYTES: usize = 33554432;
pub const STORAGE_ROWS: usize = 4096;
/// An app: its manifest and its descriptor or initial values, in bytes, and its longest
/// asset path; one asset's bytes, the asset count and their total bytes; and the largest
/// image it may carry, per side and in pixels.
#[cfg(feature = "storage")]
pub(crate) const MANIFEST_BYTES: usize = 65536;
pub(crate) const APP_TEXT_BYTES: usize = 4194304;
#[cfg(feature = "storage")]
pub(crate) const ASSET_PATH_BYTES: usize = 240;
pub const ASSET_FILE_BYTES: usize = 26214400;
pub const ASSET_COUNT: usize = 256;
pub const ASSET_BYTES: usize = 52428800;
pub const IMAGE_SIDE: usize = 16384;
pub const IMAGE_PIXELS: usize = 24000000;
/// A document's attachments: one file's bytes, their total bytes and their count.
pub const ATTACHMENT_FILE_BYTES: usize = 10485760;
pub const ATTACHMENT_BYTES: usize = 104857600;
pub const ATTACHMENT_COUNT: usize = 256;
/// A window shape's longest path data and radius list, and its largest view box side.
pub(crate) const SHAPE_PATH: usize = 4096;
pub(crate) const SHAPE_RADIUS: usize = 256;
pub(crate) const SHAPE_VIEW_BOX: f64 = 16384.0;
/// A batch's most intents and an intent's longest path; a page request's largest payload.
pub(crate) const BATCH_INTENTS: usize = 1000;
pub(crate) const PATH_SEGMENTS: usize = 64;
pub(crate) const PAGE_PAYLOAD: usize = 4194304;
/// The largest socket request, an attachment upload; no envelope the core checks is larger.
#[cfg(feature = "storage")]
pub const SOCKET_ATTACHMENT: usize = 16777216;
#[cfg(feature = "storage")]
pub const SOCKET_REQUEST: usize = 1048576;
/// An attachment's identity: the SHA-256 of its bytes, in lowercase hex.
#[cfg(feature = "storage")]
pub(crate) fn valid_attachment_id(id: &str) -> bool {
    id.len() == 64 && id.bytes().all(|b| b"0123456789abcdef".contains(&b))
}
pub(crate) fn valid_id(value: &str) -> bool {
    !value.is_empty() && value.len() <= 64 && value.bytes().all(|b| b"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz_-".contains(&b))
}
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(untagged, deny_unknown_fields)]
pub enum Segment {
    Key(String),
    Id { id: String },
    Index { index: usize },
}
#[derive(Debug, Deserialize)]
#[serde(untagged, deny_unknown_fields)]
pub enum Anchor {
    Before { before: String },
    After { after: String },
}
#[derive(Clone, Debug, PartialEq, Serialize)]
#[serde(untagged, deny_unknown_fields)]
pub enum Hunk {
    Retain { retain: usize },
    Insert { insert: String },
    Delete { delete: usize },
}
#[derive(Debug, Serialize)]
#[serde(tag = "type", rename_all = "camelCase")]
pub enum PatchOp {
    Set { path: Vec<Segment>, value: Value },
    Text { path: Vec<Segment>, delta: Vec<Hunk> },
    Remove { path: Vec<Segment> },
    InsertRow { path: Vec<Segment>, index: usize, value: Value },
    DeleteRow { path: Vec<Segment>, id: String },
    MoveRow { path: Vec<Segment>, id: String, index: usize },
}
impl PatchOp {
    pub fn path(&self) -> &[Segment] { match self {
        Self::Set { path, .. } => path,
        Self::Text { path, .. } => path,
        Self::Remove { path, .. } => path,
        Self::InsertRow { path, .. } => path,
        Self::DeleteRow { path, .. } => path,
        Self::MoveRow { path, .. } => path,
    } }
}
#[derive(Debug, Serialize)]
pub struct Publication { pub previous: u64, pub sequence: u64, pub version: String, pub ops: Vec<PatchOp>, #[serde(skip_serializing_if = "Option::is_none")] pub theme: Option<std::collections::BTreeMap<String, String>> }
#[derive(Debug, Deserialize)]
#[serde(tag = "type", rename_all = "camelCase", deny_unknown_fields)]
pub enum Intent {
    Set { path: Vec<Segment>, value: Value, from: Option<String>, selection: Option<Selection> },
    Insert { path: Vec<Segment>, value: Value, id: Option<String>, at: Option<Anchor>, index: Option<usize> },
    Remove { path: Vec<Segment>, id: Option<String>, index: Option<usize>, count: Option<usize> },
    Move { path: Vec<Segment>, id: String, at: Option<Anchor> },
    Clear { path: Vec<Segment> },
    Increment { path: Vec<Segment>, by: i64 },
    Replace { path: Vec<Segment>, value: Value },
    SetTheme { values: std::collections::BTreeMap<String, Option<String>>, replace: Option<bool> },
    ImportTheme { file: String },
}
impl Intent {
    /// The data path; palette intents have none.
    pub fn path(&self) -> &[Segment] { match self {
        Self::Set { path, .. } => path,
        Self::Insert { path, .. } => path,
        Self::Remove { path, .. } => path,
        Self::Move { path, .. } => path,
        Self::Clear { path, .. } => path,
        Self::Increment { path, .. } => path,
        Self::Replace { path, .. } => path,
        Self::SetTheme { .. } => &[],
        Self::ImportTheme { .. } => &[],
    } }
}
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
#[allow(non_snake_case)]
pub struct Batch { pub ifVersion: Option<String>, pub command: Option<String>, pub base: Option<String>, pub intents: Vec<Intent> }
/// A text selection in UTF-16 offsets.
#[derive(Clone, Copy, Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Selection { pub start: usize, pub end: usize }
/// A shared theme file: the template it was made for and its palette.
#[derive(Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ThemeFile { pub template: String, pub values: std::collections::BTreeMap<String, String> }
/// A built app (a build's `app.json`), as the file engine packs it into the `app` row.
/// Each part stays the JSON text the build wrote: its own validator reads it, in order.
#[cfg(feature = "storage")]
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
#[allow(non_snake_case)]
pub struct AppRow { pub packageFormat: u64, pub runtimeABI: u64, pub manifest: Box<serde_json::value::RawValue>, pub descriptor: Box<serde_json::value::RawValue>, pub initial: Box<serde_json::value::RawValue>, pub theme: Box<serde_json::value::RawValue> }


#[cfg(feature = "storage")]
#[derive(Debug, Serialize)]
#[serde(tag = "method", deny_unknown_fields)]
#[allow(non_snake_case)]
pub enum EngineRequest {
    #[serde(rename = "attachments.list")]
    AttachmentsList { documentPath: String },
    #[serde(rename = "attachments.read")]
    AttachmentsRead { documentPath: String, attachmentID: String },
    #[serde(rename = "theme.export")]
    ThemeExport { documentPath: String },
    #[serde(rename = "get")]
    Get { documentPath: String },
    #[serde(rename = "batch")]
    Batch { documentPath: String, #[serde(skip_serializing_if = "Option::is_none")] ifVersion: Option<String>, #[serde(skip_serializing_if = "Option::is_none")] command: Option<String>, ops: String, #[serde(skip_serializing_if = "Option::is_none")] base: Option<String>, #[serde(skip_serializing_if = "Option::is_none")] attachments: Option<Vec<String>> },
    #[serde(rename = "export")]
    Export { documentPath: String, format: String, output: String },
    #[serde(rename = "templates")]
    Templates {  },
    #[serde(rename = "create")]
    Create { from: String, output: String },
    #[serde(rename = "inspect")]
    Inspect { file: String },
    #[serde(rename = "schema")]
    Schema { file: String },
    #[serde(rename = "pack")]
    Pack { stage: String, file: String },
    #[serde(rename = "validateApp")]
    ValidateApp { app: Box<serde_json::value::RawValue> },
    #[serde(rename = "describe")]
    Describe { documentPath: String },
    #[serde(rename = "call")]
    Call { documentPath: String, command: String, args: Box<serde_json::value::RawValue> },
    #[serde(rename = "open")]
    Open { documentPath: String },
    #[serde(rename = "screenshot")]
    Screenshot { documentPath: String, output: String, target: String, ifPresent: bool },
}

#[cfg(feature = "storage")]
impl EngineRequest {
    /// Parse each member directly from JSON so opaque payloads retain their bytes.
    pub fn parse(input: &str) -> serde_json::Result<Self> {
        #[derive(Deserialize)] struct Header { method: String }
        let header: Header = serde_json::from_str(input)?;
        match header.method.as_str() {
            "attachments.list" => {
                #[derive(Deserialize)]
                #[serde(deny_unknown_fields)]
                #[allow(non_snake_case, dead_code)]
                struct Body { method: String, documentPath: String }
                let body: Body = serde_json::from_str(input)?;
                Ok(Self::AttachmentsList { documentPath: body.documentPath })
            },
            "attachments.read" => {
                #[derive(Deserialize)]
                #[serde(deny_unknown_fields)]
                #[allow(non_snake_case, dead_code)]
                struct Body { method: String, documentPath: String, attachmentID: String }
                let body: Body = serde_json::from_str(input)?;
                Ok(Self::AttachmentsRead { documentPath: body.documentPath, attachmentID: body.attachmentID })
            },
            "theme.export" => {
                #[derive(Deserialize)]
                #[serde(deny_unknown_fields)]
                #[allow(non_snake_case, dead_code)]
                struct Body { method: String, documentPath: String }
                let body: Body = serde_json::from_str(input)?;
                Ok(Self::ThemeExport { documentPath: body.documentPath })
            },
            "get" => {
                #[derive(Deserialize)]
                #[serde(deny_unknown_fields)]
                #[allow(non_snake_case, dead_code)]
                struct Body { method: String, documentPath: String }
                let body: Body = serde_json::from_str(input)?;
                Ok(Self::Get { documentPath: body.documentPath })
            },
            "batch" => {
                #[derive(Deserialize)]
                #[serde(deny_unknown_fields)]
                #[allow(non_snake_case, dead_code)]
                struct Body { method: String, documentPath: String, ifVersion: Option<String>, command: Option<String>, ops: String, base: Option<String>, attachments: Option<Vec<String>> }
                let body: Body = serde_json::from_str(input)?;
                Ok(Self::Batch { documentPath: body.documentPath, ifVersion: body.ifVersion, command: body.command, ops: body.ops, base: body.base, attachments: body.attachments })
            },
            "export" => {
                #[derive(Deserialize)]
                #[serde(deny_unknown_fields)]
                #[allow(non_snake_case, dead_code)]
                struct Body { method: String, documentPath: String, format: String, output: String }
                let body: Body = serde_json::from_str(input)?;
                Ok(Self::Export { documentPath: body.documentPath, format: body.format, output: body.output })
            },
            "templates" => {
                #[derive(Deserialize)]
                #[serde(deny_unknown_fields)]
                #[allow(non_snake_case, dead_code)]
                struct Body { method: String,  }
                let _body: Body = serde_json::from_str(input)?;
                Ok(Self::Templates {  })
            },
            "create" => {
                #[derive(Deserialize)]
                #[serde(deny_unknown_fields)]
                #[allow(non_snake_case, dead_code)]
                struct Body { method: String, from: String, output: String }
                let body: Body = serde_json::from_str(input)?;
                Ok(Self::Create { from: body.from, output: body.output })
            },
            "inspect" => {
                #[derive(Deserialize)]
                #[serde(deny_unknown_fields)]
                #[allow(non_snake_case, dead_code)]
                struct Body { method: String, file: String }
                let body: Body = serde_json::from_str(input)?;
                Ok(Self::Inspect { file: body.file })
            },
            "schema" => {
                #[derive(Deserialize)]
                #[serde(deny_unknown_fields)]
                #[allow(non_snake_case, dead_code)]
                struct Body { method: String, file: String }
                let body: Body = serde_json::from_str(input)?;
                Ok(Self::Schema { file: body.file })
            },
            "pack" => {
                #[derive(Deserialize)]
                #[serde(deny_unknown_fields)]
                #[allow(non_snake_case, dead_code)]
                struct Body { method: String, stage: String, file: String }
                let body: Body = serde_json::from_str(input)?;
                Ok(Self::Pack { stage: body.stage, file: body.file })
            },
            "validateApp" => {
                #[derive(Deserialize)]
                #[serde(deny_unknown_fields)]
                #[allow(non_snake_case, dead_code)]
                struct Body { method: String, app: Box<serde_json::value::RawValue> }
                let body: Body = serde_json::from_str(input)?;
                Ok(Self::ValidateApp { app: body.app })
            },
            "describe" => {
                #[derive(Deserialize)]
                #[serde(deny_unknown_fields)]
                #[allow(non_snake_case, dead_code)]
                struct Body { method: String, documentPath: String }
                let body: Body = serde_json::from_str(input)?;
                Ok(Self::Describe { documentPath: body.documentPath })
            },
            "call" => {
                #[derive(Deserialize)]
                #[serde(deny_unknown_fields)]
                #[allow(non_snake_case, dead_code)]
                struct Body { method: String, documentPath: String, command: String, args: Box<serde_json::value::RawValue> }
                let body: Body = serde_json::from_str(input)?;
                Ok(Self::Call { documentPath: body.documentPath, command: body.command, args: body.args })
            },
            "open" => {
                #[derive(Deserialize)]
                #[serde(deny_unknown_fields)]
                #[allow(non_snake_case, dead_code)]
                struct Body { method: String, documentPath: String }
                let body: Body = serde_json::from_str(input)?;
                Ok(Self::Open { documentPath: body.documentPath })
            },
            "screenshot" => {
                #[derive(Deserialize)]
                #[serde(deny_unknown_fields)]
                #[allow(non_snake_case, dead_code)]
                struct Body { method: String, documentPath: String, output: String, target: String, ifPresent: bool }
                let body: Body = serde_json::from_str(input)?;
                Ok(Self::Screenshot { documentPath: body.documentPath, output: body.output, target: body.target, ifPresent: body.ifPresent })
            },
            _ => Err(<serde_json::Error as serde::de::Error>::custom("Unknown engine method")),
        }
    }
    pub fn method(&self) -> &'static str { match self {
        Self::AttachmentsList { .. } => "attachments.list",
        Self::AttachmentsRead { .. } => "attachments.read",
        Self::ThemeExport { .. } => "theme.export",
        Self::Get { .. } => "get",
        Self::Batch { .. } => "batch",
        Self::Export { .. } => "export",
        Self::Templates { .. } => "templates",
        Self::Create { .. } => "create",
        Self::Inspect { .. } => "inspect",
        Self::Schema { .. } => "schema",
        Self::Pack { .. } => "pack",
        Self::ValidateApp { .. } => "validateApp",
        Self::Describe { .. } => "describe",
        Self::Call { .. } => "call",
        Self::Open { .. } => "open",
        Self::Screenshot { .. } => "screenshot",
    } }
}

#[cfg(feature = "storage")]
#[derive(Debug, Serialize)]
#[serde(tag = "method", deny_unknown_fields)]
#[allow(non_snake_case)]
pub enum EngineSuccess {
    #[serde(rename = "get")]
    Get { state: Box<serde_json::value::RawValue> },
    #[serde(rename = "batch")]
    Batch { ids: Vec<String> },
    #[serde(rename = "export")]
    Export { output: String },
    #[serde(rename = "theme.export")]
    ThemeExport { state: Box<serde_json::value::RawValue> },
    #[serde(rename = "attachments.list")]
    AttachmentsList { state: Box<serde_json::value::RawValue> },
    #[serde(rename = "attachments.read")]
    AttachmentsRead { state: Box<serde_json::value::RawValue> },
    #[serde(rename = "call")]
    Call { result: Box<serde_json::value::RawValue>, ids: Vec<String> },
    #[serde(rename = "templates")]
    Templates { catalog: Box<serde_json::value::RawValue> },
    #[serde(rename = "create")]
    Create { documentPath: String },
    #[serde(rename = "inspect")]
    Inspect { info: Box<serde_json::value::RawValue> },
    #[serde(rename = "schema")]
    Schema { schema: Box<serde_json::value::RawValue> },
    #[serde(rename = "pack")]
    Pack {  },
    #[serde(rename = "validateApp")]
    ValidateApp {  },
    #[serde(rename = "describe")]
    Describe { state: Box<serde_json::value::RawValue> },
    #[serde(rename = "open")]
    Open { documentPath: String },
    #[serde(rename = "screenshot")]
    Screenshot { output: Box<serde_json::value::RawValue> },
}


#[cfg(feature = "storage")]
#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(tag = "method", deny_unknown_fields)]
#[allow(non_snake_case)]
pub(crate) enum SocketRequest {
    #[serde(rename = "attachments.list")]
    AttachmentsList { protocol: u64, documentPath: String },
    #[serde(rename = "attachments.read")]
    AttachmentsRead { protocol: u64, documentPath: String, attachmentID: String },
    #[serde(rename = "theme.export")]
    ThemeExport { protocol: u64, documentPath: String },
    #[serde(rename = "get")]
    Get { protocol: u64, documentPath: String },
    #[serde(rename = "batch")]
    Batch { protocol: u64, documentPath: String, #[serde(skip_serializing_if = "Option::is_none")] ifVersion: Option<String>, #[serde(skip_serializing_if = "Option::is_none")] command: Option<String>, ops: String, #[serde(skip_serializing_if = "Option::is_none")] base: Option<String>, #[serde(skip_serializing_if = "Option::is_none")] attachments: Option<Vec<String>> },
    #[serde(rename = "export")]
    Export { protocol: u64, documentPath: String, format: String, output: String },
}

#[cfg(feature = "storage")]
impl SocketRequest {
    pub fn method(&self) -> &'static str { match self {
        Self::AttachmentsList { .. } => "attachments.list",
        Self::AttachmentsRead { .. } => "attachments.read",
        Self::ThemeExport { .. } => "theme.export",
        Self::Get { .. } => "get",
        Self::Batch { .. } => "batch",
        Self::Export { .. } => "export",
    } }
    pub fn path(&self) -> &str { match self {
        Self::AttachmentsList { documentPath, .. } => documentPath,
        Self::AttachmentsRead { documentPath, .. } => documentPath,
        Self::ThemeExport { documentPath, .. } => documentPath,
        Self::Get { documentPath, .. } => documentPath,
        Self::Batch { documentPath, .. } => documentPath,
        Self::Export { documentPath, .. } => documentPath,
    } }
}
/// A page request. The core answers the document requests; the window's own (config,
/// readiness, resizing, errors) are the host's, so their fields go unread here.
#[cfg(feature = "storage")]
#[derive(Debug, Deserialize)]
#[serde(tag = "method", deny_unknown_fields)]
#[allow(non_snake_case, dead_code)]
pub(crate) enum PageRequest {
    #[serde(rename = "open")]
    Open {  },
    #[serde(rename = "apply")]
    Apply { batch: String },
    #[serde(rename = "flush")]
    Flush {  },
    #[serde(rename = "undo")]
    Undo {  },
    #[serde(rename = "redo")]
    Redo {  },
    #[serde(rename = "config")]
    Config {  },
    #[serde(rename = "attachments.put")]
    AttachmentsPut { bytes: String },
    #[serde(rename = "attachments.read")]
    AttachmentsRead { attachmentID: String },
    #[serde(rename = "window.resize")]
    WindowResize { width: u64, height: u64 },
    #[serde(rename = "ready")]
    Ready {  },
    #[serde(rename = "pageRecovered")]
    PageRecovered {  },
    #[serde(rename = "failed")]
    Failed { error: String },
    #[serde(rename = "pageError")]
    PageError { kind: String, error: String },
}


#[cfg(feature = "storage")]
#[derive(Debug, Serialize)]
#[serde(tag = "method", deny_unknown_fields)]
#[allow(non_snake_case)]
pub(crate) enum SocketSuccess {
    #[serde(rename = "get")]
    Get { state: Box<serde_json::value::RawValue> },
    #[serde(rename = "batch")]
    Batch { ids: Vec<String> },
    #[serde(rename = "export")]
    Export { output: String },
    #[serde(rename = "theme.export")]
    ThemeExport { state: Box<serde_json::value::RawValue> },
    #[serde(rename = "attachments.list")]
    AttachmentsList { state: Box<serde_json::value::RawValue> },
    #[serde(rename = "attachments.read")]
    AttachmentsRead { state: Box<serde_json::value::RawValue> },
}

#[cfg(feature = "storage")]
#[derive(Clone, Copy, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub(crate) enum OutcomeCode { Rejected, OwnerReplaced, Closing, SaveFailed, OwnerInvalidated, UnknownOutcome }
#[cfg(feature = "storage")]
#[derive(Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
#[allow(non_snake_case)]
pub(crate) struct SocketFailure {
    pub error: String,
    pub code: OutcomeCode,
    #[serde(skip_serializing_if = "Option::is_none")] pub reason: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")] pub opIndex: Option<u32>,
}
