import { defineTheme } from "@hitslop/runtime/theme";

export default defineTheme({
  surface: "#fbf9ff",
  paper: "#ffffff",
  lilac: "#efe9ff",
  line: "#c4b5fd",
  ink: "#1e1b4b",
  muted: "#5b5778",
  dim: "#8a86a8",
  accent: "#5b4fe0",
  onAccent: "#ffffff",
  focus: "#4f46e5",
  rule: "color-mix(in srgb, #1e1b4b 12%, transparent)",
  ruleStrong: "color-mix(in srgb, #1e1b4b 28%, transparent)",
  danger: "#e11d48",
  error: "#7b2630",
  flt: "#4f46e5",
  fltBg: "#e0e7ff",
  htl: "#b45309",
  htlBg: "#fef3c7",
  dine: "#be123c",
  dineBg: "#ffe4e6",
  rail: "#0f766e",
  railBg: "#ccfbf1",
  act: "#047857",
  actBg: "#d1fae5",
  font: '"Avenir Next", "Helvetica Neue", sans-serif',
  mono: 'ui-monospace, "SFMono-Regular", Menlo, Monaco, Consolas, monospace',
});
