import { variants, OperationSchema } from "./contract";
import { mkdir } from "node:fs/promises";
const declarations: string[] = [];
const name = (s: string) => s[0]!.toUpperCase() + s.slice(1);
for (const [kind, fields] of Object.entries(variants)) {
  const props = Object.entries(fields).map(([key, schema]) => {
    const type =
      key === "path"
        ? "[JSONValue]"
        : schema.type === "string"
          ? "String"
          : schema.type === "integer"
            ? "Int"
            : schema.type === "number"
              ? "Double"
              : "JSONValue";
    return { key, type };
  });
  declarations.push(
    `public struct ${name(kind)}Op: Codable, Sendable {\n${props.map(({ key, type }) => `  public let ${key}: ${type}`).join("\n")}\n  public init(${props.map(({ key, type }) => `${key}: ${type}`).join(", ")}) { ${props.map(({ key }) => `self.${key} = ${key}`).join("; ")} }\n}`,
  );
}
const cases = Object.keys(variants);
const swift = `// Generated by bun spikes/engine-placement/generate.ts. Do not edit.\nimport Foundation\n${declarations.join("\n")}\npublic enum Operation: Codable, Sendable {\n${cases.map((k) => `  case ${k}(${name(k)}Op)`).join("\n")}\n  enum Keys: String, CodingKey { case type }\n  public init(from decoder: Decoder) throws {\n    let key = try decoder.container(keyedBy: Keys.self).decode(String.self, forKey: .type)\n    switch key {\n${cases.map((k) => `    case "${k}": self = .${k}(try ${name(k)}Op(from: decoder))`).join("\n")}\n    default: throw SpikeError("Unknown operation: \\(key)")\n    }\n  }\n  public func encode(to encoder: Encoder) throws {\n    var c = encoder.container(keyedBy: Keys.self)\n    switch self {\n${cases.map((k) => `    case .${k}(let v): try c.encode("${k}", forKey: .type); try v.encode(to: encoder)`).join("\n")}\n    }\n  }\n  public var path: [JSONValue] { switch self {\n${cases.map((k) => `    case .${k}(let v): v.path`).join("\n")}\n  } }\n}\n`;
const output = new URL("./Sources/SpikeCore/Operations.generated.swift", import.meta.url);
if (process.argv.includes("--check")) {
  if ((await Bun.file(output).text()) !== swift) throw new Error("Spike contract drift");
} else {
  await Bun.write(output, swift);
  await mkdir(new URL("./dist", import.meta.url), { recursive: true });
  await Bun.write(
    new URL("./dist/operation.schema.json", import.meta.url),
    JSON.stringify(OperationSchema),
  );
}
