import { defineTheme } from "@hitslop/runtime/theme";

export default defineTheme({
  surface: "#ffffff",
  paper: "#ffffff",
  wash: "#f0f4f9",
  ink: "#172b4d",
  muted: "#50617a",
  dim: "#66758b",
  faint: "#c0cbdb",
  accent: "#2563eb",
  onAccent: "#ffffff",
  packed: "#059669",
  packedBg: "#d1fae5",
  stamp: "#b91c1c",
  star: "#cf4e39",
  border: "#dce3ed",
  dark: "#b5c1d1",
  control: "#e8eef5",
  ready: "#dbeafe",
  readyInk: "#1e40af",
  brass: "#b8c5d5",
  brassInner: "#75849a",
  cobalt: "#1e40af",
  cobaltBg: "#eff6ff",
  vermilion: "#b91c1c",
  vermilionBg: "#fef2f2",
  emerald: "#047857",
  emeraldBg: "#ecfdf5",
  amber: "#a94330",
  amberBg: "#fff0e9",
  plum: "#6d28d9",
  plumBg: "#f5f3ff",
  slate: "#475569",
  slateBg: "#f1f5f9",
  airmailRed: "#dc2626",
  airmailBlue: "#2563eb",
  font: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
  mono: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
});
