import AppKit
import QuickLookThumbnailing

/// Finder thumbnails are generated by the host and stored in the document.
/// This extension never loads `app.html` or executes guest code.
final class ThumbnailProvider: QLThumbnailProvider {
    override func provideThumbnail(
        for request: QLFileThumbnailRequest,
        _ handler: @escaping (QLThumbnailReply?, (any Error)?) -> Void
    ) {
        let packageURL = request.fileURL
        let scoped = packageURL.startAccessingSecurityScopedResource()
        defer { if scoped { packageURL.stopAccessingSecurityScopedResource() } }

        let quickLook = packageURL.appendingPathComponent("QuickLook", isDirectory: true)
        let thumbnail = quickLook.appendingPathComponent("Thumbnail.png")
        let preview = quickLook.appendingPathComponent("Preview.png")
        let imageURL = FileManager.default.fileExists(atPath: thumbnail.path) ? thumbnail : preview

        guard let image = NSImage(contentsOf: imageURL), image.size.width > 0, image.size.height > 0 else {
            handler(nil, CocoaError(.fileNoSuchFile))
            return
        }

        let contextSize = request.maximumSize
        let scale = min(contextSize.width / image.size.width, contextSize.height / image.size.height)
        let drawnSize = CGSize(width: image.size.width * scale, height: image.size.height * scale)
        let rect = CGRect(
            x: (contextSize.width - drawnSize.width) / 2,
            y: (contextSize.height - drawnSize.height) / 2,
            width: drawnSize.width,
            height: drawnSize.height
        )
        let reply = QLThumbnailReply(contextSize: contextSize, currentContextDrawing: {
            image.draw(in: rect)
            return true
        })
        handler(reply, nil)
    }
}
