// Generated by generate-contract.ts. Do not edit.
export type JSONValue = null | boolean | number | string | JSONValue[] | { [key: string]: JSONValue };
export type Frame<T = JSONValue> = { publication: number; revision: string; data: T; dirty: boolean; error: string | null; projectionError: string | null; };
export type Edit = { session: string; sequence: number; base: string; after: JSONValue; draft?: string; parent?: number; };
export type TextPolicy = "ancestry" | "host-frame";
