import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { FrameSchema, EditSchema, RequestSchema, Methods, ConfirmationSchema, TextPolicySchema } from "../../packages/schema/experiments/native-spike-bridge";

const optional = (schema: any, key: string) => !schema.required.includes(key);
function swiftType(property: any): string {
  if (property.$ref) return "SpikeJSON";
  if (property.anyOf) {
    const other = property.anyOf.filter((s: any) => s.type !== "null");
    if (other.length === 1 && other.length < property.anyOf.length) return swiftType(other[0]) + "?";
  }
  const result = ({ integer: "Int", number: "Double", boolean: "Bool", string: "String" } as Record<string,string>)[property.type];
  if (!result) throw new Error(`Unsupported native contract property: ${JSON.stringify(property)}`);
  return result;
}
function model(name: string, schema: any) {
  const fields = Object.entries(schema.properties).map(([key, property]) => {
    const type = swiftType(property), nullable = optional(schema, key);
    return { key, type: type + (nullable && !type.endsWith("?") ? "?" : ""), default: nullable ? " = nil" : "", optional: nullable };
  });
  return `package struct ${name}: Codable, Equatable, Sendable {\n${fields.map(f => `    package let ${f.key}: ${f.type}`).join("\n")}\n    package init(${fields.map(f => `${f.key}: ${f.type}${f.default}`).join(", ")}) {\n${fields.map(f => `        self.${f.key} = ${f.key}`).join("\n")}\n    }\n    package func encode(to encoder: any Encoder) throws {\n        var values = encoder.container(keyedBy: CodingKeys.self)\n${fields.map(f => `        try values.${f.optional ? "encodeIfPresent" : "encode"}(${f.key}, forKey: .${f.key})`).join("\n")}\n    }\n}\n`;
}
const enumeration = (name: string, values: readonly string[]) => `package enum ${name}: String, Codable, Sendable, CaseIterable {\n${values.map(v => `    case ${v.replace(/-([a-z])/g, (_,c) => c.toUpperCase())} = "${v}"`).join("\n")}\n}\n`;
const source = `// Generated by bun scripts/native-loro/generate-contract.ts. Do not edit.\nimport Foundation\nimport DynamicJSON\nimport HitSlopCore\n\n${model("SpikeFrame", FrameSchema)}\n${model("SpikeEdit", EditSchema)}\n${enumeration("SpikeConfirmation", ConfirmationSchema.enum)}\n${enumeration("SpikeTextPolicy", TextPolicySchema.enum)}\n${enumeration("SpikeMethod", Object.keys(Methods))}\npackage enum SpikeContract {\n    private static let request = ##"${JSON.stringify(RequestSchema)}"##\n    package static func validate(_ bytes: Data) throws {\n        let schema = try JSONSchema(data: Data(request.utf8))\n        guard try JSON(data: bytes).validate(with: schema, dialect: SlopJSONValidation.dialect).isValid else { throw SpikeFailure("Invalid native document request") }\n    }\n}\n`;
const path = resolve(import.meta.dir, "../../apps/apple/Packages/HitSlopApple/Sources/HitSlopLoroSpike/SpikeContract.generated.swift");
function tsType(p: any): string {
  if (p.$ref) return "JSONValue";
  if (p.anyOf) return p.anyOf.map(tsType).join(" | ");
  return p.type === "null" ? "null" : p.type === "integer" ? "number" : p.type;
}
const tsModel = (name: string, s: any) => `export type ${name} = { ${Object.entries(s.properties).map(([k,p]) => `${k}${optional(s,k) ? "?" : ""}: ${k === "data" ? "T" : tsType(p)};`).join(" ")} };`;
const client = `// Generated by generate-contract.ts. Do not edit.\nexport type JSONValue = null | boolean | number | string | JSONValue[] | { [key: string]: JSONValue };\n${tsModel("Frame<T = JSONValue>", FrameSchema)}\n${tsModel("Edit", EditSchema)}\nexport type TextPolicy = ${TextPolicySchema.enum.map(value => JSON.stringify(value)).join(" | ")};\n`;
for (const [target, bytes] of [[path, source], [resolve(import.meta.dir, "contract.generated.ts"), client]]) {
  if (process.argv.includes("--check")) {
    if (await readFile(target!, "utf8") !== bytes) throw new Error("Native spike bridge contract is stale");
  } else await writeFile(target!, bytes!);
}
