<script lang="ts">
  import { Dialog } from "bits-ui";
  import { jsonStore } from "@slop/svelte";
  import Check from "@lucide/svelte/icons/check"; import Plus from "@lucide/svelte/icons/plus"; import Trash2 from "@lucide/svelte/icons/trash-2"; import X from "@lucide/svelte/icons/x";
  type Entry={id:number;day:string;time:string;title:string;done:boolean}; type Planner={week:string;focus:string;entries:Entry[];nextID:number};
  const planner=jsonStore<Planner>("state",{week:"This week",focus:"",entries:[],nextID:1}); const days=["MON","TUE","WED","THU","FRI","SAT","SUN"];
  let adding=$state(false);let editingID=$state<number|null>(null);let day=$state("MON");let time=$state("");let title=$state("");
  function toggle(id:number):void{planner.update(data=>{const item=data.entries.find(entry=>entry.id===id);if(item)item.done=!item.done})}
  function beginAdd(nextDay:string):void{editingID=null;day=nextDay;time="";title="";adding=true}
  function beginEdit(entry:Entry):void{editingID=entry.id;day=entry.day;time=entry.time;title=entry.title;adding=true}
  function save():void{const clean=title.trim();if(!clean)return;planner.update(data=>{if(editingID===null){data.entries.push({id:data.nextID,day,time,title:clean,done:false});data.nextID+=1}else{const item=data.entries.find(entry=>entry.id===editingID);if(item){item.day=day;item.time=time;item.title=clean}}});title="";time="";editingID=null;adding=false}
  function remove():void{if(editingID===null)return;planner.update(data=>{data.entries=data.entries.filter(entry=>entry.id!==editingID)});editingID=null;adding=false}
  function setText(key:"week"|"focus",value:string):void{planner.update(data=>{data[key]=value})}
</script>
<main class="planner" data-slop-selection="none"><header><div><p>WEEK / 35</p><input aria-label="Week label" value={planner.current.week} oninput={(e)=>setText("week",e.currentTarget.value)}/></div><label>One clear priority<input value={planner.current.focus} oninput={(e)=>setText("focus",e.currentTarget.value)}/></label></header><section class="week">{#each days as current,index}<article class:today={current==="THU"}><div class="day-head"><span>{String(index+24).padStart(2,"0")}</span><h2>{current}</h2><button aria-label={`Add on ${current}`} onclick={()=>beginAdd(current)}><Plus/></button></div><ol>{#each planner.current.entries.filter(entry=>entry.day===current) as entry (entry.id)}<li class:done={entry.done}><button onclick={()=>toggle(entry.id)} aria-label={entry.done?"Mark incomplete":"Mark complete"}>{#if entry.done}<Check/>{/if}</button><button class="entry-copy" onclick={()=>beginEdit(entry)} aria-label={`Edit ${entry.title}`}><time>{entry.time||"Any time"}</time><strong>{entry.title}</strong></button></li>{/each}</ol></article>{/each}</section><footer><span>{planner.current.entries.filter(item=>item.done).length} complete</span><span>Tap an entry to edit</span></footer>
<Dialog.Root bind:open={adding}><Dialog.Portal><Dialog.Overlay class="overlay"/><Dialog.Content class="dialog"><form onsubmit={(event)=>{event.preventDefault();save()}}><p>{editingID===null?`ADD TO ${day}`:"EDIT ENTRY"}</p><Dialog.Title>{editingID===null?"Make time for it.":"Adjust the plan."}</Dialog.Title><label>What<input bind:value={title} placeholder="Write the next useful thing"/></label><label>Time<input bind:value={time} placeholder="09:30"/></label><label>Day<select bind:value={day}>{#each days as option}<option value={option}>{option}</option>{/each}</select></label><div>{#if editingID!==null}<button class="remove" type="button" onclick={remove} aria-label="Delete entry"><Trash2/>Delete</button>{/if}<Dialog.Close type="button">Cancel</Dialog.Close><button type="submit">{editingID===null?"Add entry":"Save changes"}</button></div></form><Dialog.Close class="close" aria-label="Close"><X/></Dialog.Close></Dialog.Content></Dialog.Portal></Dialog.Root></main>
