<script lang="ts">
  import { Tabs } from "bits-ui"; import { jsonStore } from "@slop/svelte"; import MapPin from "@lucide/svelte/icons/map-pin"; import Plane from "@lucide/svelte/icons/plane"; import Plus from "@lucide/svelte/icons/plus";
  type Event={id:number;time:string;title:string;place:string};type Day={id:string;label:string;date:string;events:Event[]};type Trip={trip:string;route:string;dates:string;days:Day[];nextID:number};
  const trip=jsonStore<Trip>("state",{trip:"New trip",route:"YXE → LIS",dates:"",days:[],nextID:1});let selected=$state("01");
  const active=$derived(trip.current.days.find(day=>day.id===selected)??trip.current.days[0]);
  function setField(key:"trip"|"route"|"dates",value:string):void{trip.update(data=>{data[key]=value})}
  function updateEvent(id:number,key:"time"|"title"|"place",value:string):void{if(!active)return;trip.update(data=>{const event=data.days.find(item=>item.id===active.id)?.events.find(item=>item.id===id);if(event)event[key]=value})}
  function addEvent():void{if(!active)return;trip.update(data=>{const day=data.days.find(item=>item.id===active.id);if(day){day.events.push({id:data.nextID,time:"12:00",title:"New stop",place:"Add a place"});data.nextID+=1}})}
</script>
<main class="trip" data-slop-selection="none"><header><label class="route"><Plane/><input aria-label="Trip route" value={trip.current.route} oninput={(e)=>setField("route",e.currentTarget.value)}/></label><input aria-label="Trip title" value={trip.current.trip} oninput={(e)=>setField("trip",e.currentTarget.value)}/><input class="trip-dates" aria-label="Trip dates" value={trip.current.dates} placeholder="Add travel dates" oninput={(e)=>setField("dates",e.currentTarget.value)}/></header><Tabs.Root bind:value={selected}><Tabs.List class="day-tabs" aria-label="Trip days">{#each trip.current.days as day}<Tabs.Trigger value={day.id}><span>{day.id}</span><strong>{day.label}</strong><small>{day.date}</small></Tabs.Trigger>{/each}</Tabs.List>{#if active}<Tabs.Content value={active.id} class="schedule"><div class="schedule-head"><div><span>DAY {active.id}</span><h2>{active.label.toLowerCase()}, loosely.</h2></div><button onclick={addEvent}><Plus/>Add stop</button></div><ol>{#each active.events as event,index (event.id)}<li><input class="event-time" aria-label={`Time for ${event.title}`} value={event.time} oninput={(e)=>updateEvent(event.id,"time",e.currentTarget.value)}/><span class="rail"><i></i></span><div><small>STOP {String(index+1).padStart(2,"0")}</small><input class="event-title" aria-label="Stop title" value={event.title} oninput={(e)=>updateEvent(event.id,"title",e.currentTarget.value)}/><label class="event-place"><MapPin/><input aria-label="Stop place" value={event.place} oninput={(e)=>updateEvent(event.id,"place",e.currentTarget.value)}/></label></div></li>{/each}</ol></Tabs.Content>{/if}</Tabs.Root><footer><span>{trip.current.days.length} days planned</span><span>Keep one afternoon empty</span></footer></main>
